### ISSUE TITLE
Verbose logging on tests

### ISSUE THREAD

**Issue by elmalto** [websudos/phantom#130]
I cant find a setting on phantom-testing to disable the massive console.log output

e.g. 

9042 available
Starting cassandra
14:48:34.974 [pool-6-thread-1] INFO  o.a.c.config.YamlConfigurationLoader - Loading settings

Is there a way to disable this?

**Comment by alexflav23** [comment]
@elmalto All loggers have been successfully moved to slf4j compatible api, which means you can configure all loggers using an xml configuration or whatever other supported config format. Perhaps a much better place to continue with this is here: http://slf4j.org/faq.html.

Hope this helps

**Comment by elmalto** [comment]
perfect, thank you
