### ISSUE TITLE
Please release a Scala 2.11 version

### ISSUE THREAD

**Issue by agemooij** [websudos/phantom#133]
Phantom looks like exactly what we need to upgrade the way we are interacting with Cassandra from Akka actors... unfortunately there is no Scala 2.11 release. Could you please provide one?

If you need any help turning your build into a cross-versioned one, please let me know and I'll submit a PR for it.

**Comment by alexflav23** [comment]
@agemooij @fbettag @magott @jasongoodwin Thanks to a lot of help from @fbettag along with the folks from Twitter and our efforts, 2.11 is now out, phantom 1.5.0 is published for both 2.10 and 2.11, on Maven Central.

**Comment by agemooij** [comment]
Awesome.Thanks everyone!

**Comment by jasongoodwin** [comment]
Thanks so much guys!

**Comment by fbettag** [comment]
Glad i could help
