### ISSUE TITLE
Error extracting value from compound key

### ISSUE THREAD

**Issue by lab3** [websudos/phantom#138]
I'm using the published dev release of 1.2.7 for Scala 2.11 

I get the following error when extracting the row values
Error: can't extract required value for column 'param_id'

The first column, decoder_key is extracted fine but the second column fails with that error.  A toString() on the row reveals all the column data is there and in tact.

CREATE TABLE answers_clustered (
  	decoder_key text,
  	param_id bigint,
  	answers set < int >,
  	first_answered timestamp,
  	last_answered timestamp,
  	expires timestamp,
  	PRIMARY KEY ( decoder_key, param_id )
);

https://gist.github.com/lab3/893f5bea365ff36c67aa

**Comment by alexflav23** [comment]
@lab3 @kuhnen There is a new version, 1.5.0, an official release with full support for Scala 2.11 in phantom. Could you please confirm if the above persists there?
