### ISSUE TITLE
Ambiguous implicits when importing import com.websudos.phantom.Implicits._

### ISSUE THREAD

**Issue by hamnis** [websudos/phantom#145]
$ sbt compile
[info] Compiling 3 Scala sources to /Users/maedhros/Projects/hbase-cassandra-migration/target/classes...
[error] /Users/maedhros/Projects/hbase-cassandra-migration/src/main/scala/hbcass/MigrateHistory.scala:72: type mismatch;
[error]  found   : ts.type (with underlying type String)
[error]  required: ?{def toLong: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
[error]  and method wrapString in class LowPriorityImplicits of type (s: String)scala.collection.immutable.WrappedString
[error]  are possible conversion functions from ts.type to ?{def toLong: ?}
[error]         List(Click(site, UserContentEvent(userId, contentId, new DateTime(ts.toLong))))
[error]                                                                           ^
[error] one error found
[error] (compile:compile) Compilation failed

**Comment by alexflav23** [comment]
@prettynatty  @magott @hamnis An official Scala 2.11 release is now out. This issue is fixed and will be closed.
