### ISSUE TITLE
A few random, mostly doc issues

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#162]
1. In a really simple app, something like the executor is not being shut down, so at the end it hangs forever.
2. It would be great to have an example of inserting.  I found it by browsing to the Recipe example, but it'd be great to have it since the rest of the documentation is so good.
3. I can see simply mixing in `SimpleCassandraConnector`, but what if I want to use it in a deployed environment, and want to configure the Cassandra host and port to talk to?  I can't just override a val, I would probably be pulling it from config.  Any examples?
4.  It seems there is a lot of boilerplate, when one mixes in a case class (for ex., `ExampleModel`) as the second type to the class that extends `CassandraTable`  (eg. `class ExampleRecord extends CassandraTable[ExampleRecord, ExampleModel]`).  Namely, still have to define an inner object for each field, plus the `fromRow` method where again every field is redefined.  Plus if I add some kind of insert method, then again all the fields are redefined.  Any way to avoid the boilerplate?

Many thanks.  Phantom seems like a great project so far.

**Comment by alexflav23** [comment]
@GoldenZero In the next milestone release, a shutdown method will be found for the executor and the docs now have examples on inserts. Many thanks for reporting this once again. We've also added examples to clarify point 3 and 4 you made.

**Comment by bbirand** [comment]
@alexflav23 Can you point out where you in the documentation you are addressing the 4. point of @velvia ? All I see is this:
https://github.com/websudos/phantom#data-modeling-with-phantom

And that section doesn't even have any text. I'm just looking at the library, and I'm not sure I understand the reasoning behind the  `fromRow` method.

My basic question is, would it not be possible to just give the case class of the object, and provide some additional data (like `PartitionKey` and `ClusteringOrder`) to the table? It just seems that the compiler can figure out that this line in the case class:
```
name: String
```
has to turn into this in the `CassandraTable`:
```
object name extends StringColumn(this)
```

As @velvia pointed out, there is also redundancy with the `fromRow`.

I feel like these points must be addressed somewhere, but I can't find where..

Thanks for this library!
