### ISSUE TITLE
Ability to set table creation options.

### ISSUE THREAD

**Issue by prettynatty** [websudos/phantom#164]
It would be great to have an ability to set options which are set after `WITH` keyboard in `CREATE TABLE` query.
It is useful for disabling row cache for example (http://www.datastax.com/documentation/cassandra/1.2/cassandra/operations/ops_set_caching_t.html)

**Comment by alexflav23** [comment]
@prettynatty We have started work on a new QueryBuilder, independent of the underlying Datastax builder. This will include a large number of improvements to the builder, from performance, to quality of compilation errors to available features.

We will post a roadmap for this sometime next week. For this this ticket will be closed and we will have a new one to explicitly deal with the full set of new features supported by the new builder.
