### ISSUE TITLE
Pattern to partially execute queries/inserts is broken.

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#166]
Let's say I'm doing lots of inserts, and there are certain column values (corresponding to parts of the primary key) which I want fixed.  This doesn't work:

```scala
    val commonStatement = insert.value(_.dataset, dataset)
                                .value(_.version, version)
                                .value(_.shard,   shard)
                                .value(_.rowId,   rowId)
    val batch = UnloggedBatchStatement()
    columnsBytes.foreach { case (columnName, bytes) =>
      batch.add(commonStatement.value(_.columnName, columnName)
                               .value(_.bytes, bytes))
    }
    batch.future()
```

leading to this error:
```
[error] (run-main-b) com.datastax.driver.core.exceptions.InvalidQueryException: Multiple definitions found for column columnname
com.datastax.driver.core.exceptions.InvalidQueryException: Multiple definitions found for column columnname
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:97)
```

However, this works:
```scala
      batch.add(insert.value(_.dataset, dataset)
                       .value(_.version, version)
                       .value(_.shard,   shard)
                       .value(_.rowId,   rowId)
                       .value(_.columnName, columnName)
                       .value(_.bytes, bytes))
```

I was thinking partially reusing the query would help performance, but maybe what I really need are prepared statements.  Anyways, any reason why the original doesn't work?

**Comment by alexflav23** [comment]
@velvia In your above example, ```batch.add``` is immutable meaning you get a whole new batch, so your foreach isn't even adding anything to the batch from where I stand. Apologies for the late reply.

**Comment by velvia** [comment]
@alexflav23  that's interesting you say that.  So the proper pattern is to do a fold or something?
Despite what you say, the code with the foreach seems to actually do the inserts.

**Comment by alexflav23** [comment]
@velvia I will double check the example, perhaps it was my mistake at first glance. Regardless, I hope everything is sorted now. Prepared statements will also hopefully come very shortly.
