### ISSUE TITLE
Release latest phantom dsl for scala 2.11 to maven central.

### ISSUE THREAD

**Issue by nbauernfeind** [websudos/phantom#169]
I noticed that http://maven.websudos.co.uk/ext-release-local only has v.1.2.7 for the scala 2.11 phantom-dsl binary. Would it be possible to release the latest 1.4.0 version of this? Also, would it be possible to release it to maven central like the 1.4.0 binaries for scala 2.10?

**Comment by alexflav23** [comment]
@nbauernfeind Phantom is now available for Scala 2.11, version 1.5.0 is on Maven Central.
