### ISSUE TITLE
eqs on Option[UUID] type?

### ISSUE THREAD

**Issue by thiagoandrade6** [websudos/phantom#173]
Hi, I'm trying to do a eqs on a Option field eg.

```
Address.select.where(_.id eqs Some(uuid)).one()
```

Then I get "value eqs  is not a member of object"

is there a way to accomplish that? I can't figure out...

The id field is an Option[UUID], because it must be null when I'm receiving a POST request in Play Framework, but I don't know how to do this assert in phantom

**Comment by alexflav23** [comment]
@thiagoandrade6 I don't think so since you cannot have an equals condition on a non indexed column and a Cassandra index cannot be null. It's not a Phantom limitation, it's a CQL design feature. The error is somewhat misleading, but it's telling you "id" is not an indexed column.

**Comment by thiagoandrade6** [comment]
Cool, I will have to figure out how to solve this problem, but thanks for the help.
