### ISSUE TITLE
Slick Like API

### ISSUE THREAD

**Issue by PeterLappo** [websudos/phantom#177]
Hi,
I quite like the API Slick in the way it appears as a Scala collection, Is there any way phantom could have a similar API so that you could mix relational and Cassandra access without changing programming styles when querying or modifying data?

Cheers
Peter

**Comment by alexflav23** [comment]
Hi @PeterLappo,

Unfortunately we don't feel Slick is a good idea and for any non trivial modelling scenarios it has proven to be a frequent target of criticism in the community, so it's not exactly deemed a great success. 

Beyond that, there isn't a strong case for such an API in Cassandra, given the modelling syntax doesn't need to abstract away query language discrepancies like it would in Slick. In general, creating new abstractions on top of established topologies is not a good course of action as we see it.

Regards,
Flavian
