### ISSUE TITLE
phantom-zookeeper 1.4.0 - 1.5.0 has unresolved dependencies

### ISSUE THREAD

**Issue by prasadmahendra** [websudos/phantom#180]
warn] 	module not found: com.twitter#finagle-zookeeper_2.10;6.24.0
[warn] ==== local: tried
[warn]   /Users/pmahendra/.ivy2/local/com.twitter/finagle-zookeeper_2.10/6.24.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/twitter/finagle-zookeeper_2.10/6.24.0/finagle-zookeeper_2.10-6.24.0.pom
[warn] ==== Typesafe Releases: tried
[warn]   http://repo.typesafe.com/typesafe/maven-releases/com/twitter/finagle-zookeeper_2.10/6.24.0/finagle-zookeeper_2.10-6.24.0.pom
[warn] ==== twitter-repo: tried
[warn]   http://maven.twttr.com/com/twitter/finagle-zookeeper_2.10/6.24.0/finagle-zookeeper_2.10-6.24.0.pom
[warn] ==== websudos-repo: tried
[warn]   http://maven.websudos.co.uk/ext-release-local/com/twitter/finagle-zookeeper_2.10/6.24.0/finagle-zookeeper_2.10-6.24.0.pom
....
....
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter#finagle-zookeeper_2.10;6.24.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by prasadmahendra** [comment]
I have both the recommended resolvers specified:

resolvers += "twitter-repo" at "http://maven.twttr.com"
resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

Did http://maven.websudos.co.uk/ext-release-local go away? lots of 404s from the server.

**Comment by alexflav23** [comment]
@prasadmahendra The issues in question should now be fixed, we've just republished those dependencies to our Maven repository. Please let us know if you experience further issues.

**Comment by arkady60** [comment]
I am getting unresolved dependency for com.twitter#finagle-zookeeper_2.10;6.17.0
In build sbt i have included
"com.websudos" % "phantom-zookeeper_2.10" % "1.2.2"

and 
resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

resolvers += "twitter-repo" at "http://maven.twttr.com"

Please advice
