### ISSUE TITLE
cassandraunit version greater than what is on maven central

### ISSUE THREAD

**Issue by sjohnc** [websudos/phantom#182]
This code depends on cassandraunit 2.0.2.4 the latest on maven central is 2.0.2.2, can you release a version that is dependent on 2.0.2.2?

**Comment by carwilki** [comment]
this is affecting me as well.

**Comment by graph1zzlle** [comment]
This is currently affecting all PRs.

**Comment by alexflav23** [comment]
@graph1zzlle @carwilki We are using a custom Cassandra Unit distribution with very minor changes to the project, simply using a newer version of Cassandra. This was also published on our Maven repo and it's now being restored to its proper place.

All PRs should return to normal very shortly.

**Comment by alexflav23** [comment]
@graph1zzlle @carwilki The appropriate version of Cassandra Unit is now available on our managed Maven repository and there should be no further interruption of service. Thank you for reporting this, please let us know if you experience further issues.
