### ISSUE TITLE
Type Mismatch on SecondaryQueryCondition

### ISSUE THREAD

**Issue by thiagoandrade6** [websudos/phantom#192]
Hi, I'm trying to do a query based on a secondary field, but I'm getting a compiler error on this:

```
val future = Validity.select.allowFiltering().where(_.clientId eqs uuid).fetch()
```

Where clientId is an index column. Indeed it works on CQL as expected, but gives me type mismatch found: SecondaryQueryCondition and required: QueryCondition.

This is the only example I've found and I would like to know how it works, please.

[Your Example](https://github.com/websudos/phantom/blob/develop/phantom-example/src/main/scala/com/websudos/phantom/example/basics/CompositeKeyRecipes.scala)

**Comment by thiagoandrade6** [comment]
Hmm, found the error...

Scala gives type mismatch when you try to do a where with an optional field...

**Comment by alexflav23** [comment]
@thiagoandrade6 That's not an error though. You can only do ```where``` with a column that's part of the ```Primary``` and you cannot have a ```null``` primary key in a table. No part of the CQL primary key can be ```null```, so optional columns cannot be used as part of an index or as part of an ```where``` clause.

Read [this article](http://blog.websudos.com/2014/08/a-series-on-cassandra-part-2-indexes-and-keys/) to understand more about the underlying mechanics, the idea is simple, if any part of the primary key would be allowed to be null, the unicity guarantee can no longer be satisfied.

**Comment by thiagoandrade6** [comment]
Hey @alexflav23 Indeed, this is not a bug or anything else, but since scala did not help me out, that type mismatch was strange, but you have explained very well why. Thanks for your attention.
