### ISSUE TITLE
thread pool executor in CassandraResultSetOperations.Manager is never shutdown

### ISSUE THREAD

**Issue by TrustNoOne** [websudos/phantom#197]
Hi,
I can't find a way of shutting down the thread pool executor in CassandraResultSetOperations.Manager:

```scala
 lazy val taskExecutor = Executors.newCachedThreadPool()
```

This leads to leaks in applications that reload classes (e.g. play).

**Comment by alexflav23** [comment]
@TrustNoOne There is indeed no direct API method to shut down the executor. We will add one in the next release, to allow controlling how and when things shutdown.

Thank you for reporting this.
