### ISSUE TITLE
No support for ALTER table

### ISSUE THREAD

**Issue by arkady60** [websudos/phantom#198]
Can you please advice on when the Support for Alter table will be provided. The idea is to be able to update CQL table based on the difference of the Actual table schema and the current columns set of phantom Cassandra Table.
Thank you

**Comment by alexflav23** [comment]
@arkady60 Hi, support for ALTER table will be included in either 1.6.0 or 1.7.0.We have already begun work on a new Query builder written in Scala to superseed the Datastax variant in phantom. This new builder will fully support all CQL options and the entire protocol, including ALTER queries.

The 1.6.0 release is scheduled for end of February, but the likely odds are the new querybuilder will reach a stable variant somewhere around end of March 2015. Hope this helps and we will keep everyone posted.
