### ISSUE TITLE
Tests automation question

### ISSUE THREAD

**Issue by fernandoj92** [websudos/phantom#206]
Hi, love this project. I am developping a Play 2.3.7 Application and I am having some trouble automating tests. 

I want to test some operations to the DB (insert,selectbyId,selectAll...etc) and if possible in a way that works with Travis.

My problem is that i receive this error:

`ERROR com.websudos.phantom - unconfigured column family devices`

I ve checked it on localhost, and i see that everytime an instert or query is executed on the test.  The thing is when i execute the test, it creates the keyspace "phantom" but it doesnt create the table "devices", so if i dont have it created by default ,it will throw an exception an show that message

On your tests i ve seen a method called `insertSchema()` that is executed before every test, but i am neither able to find its implementation in your examples nor able to import it from the sourcecode.

```scala
override def beforeAll(){
    super.beforeAll()
    Devices.insertSchema()
  }
```

The thing is i dont either know how your embedded Cassandra DB works, because after all those tests end, neither the keyspace nor the table (in this case i have created the table myself on the CQL Shell before excuting them) are being dropped, so if for example i execute a getEntireTable, i will receive a different number of items everytime, because all those rows are not being deleted by default.

I say this because i was under the impression that  on each execution of the TestSuite, the keyspce, tables, rows...etc would be created and after finishing...removed

In case you are wondering it, this is my class header code, the rest are just querys on scalaTest:
```scala
class DevicesSpec  extends PhantomCassandraTestSuite{

  //No need to specify the keyspace, its "phantom" by default
  implicit val s: PatienceConfiguration.Timeout = timeout(10 seconds)
  implicit val executor = scala.concurrent.ExecutionContext.Implicits.global

  override def beforeAll(){
    super.beforeAll()
    //Devices.create.future()
   //insertSchema()?
  }
```
Thank you for your time, and i hope you can help me with this

Fernando

**Comment by alexflav23** [comment]
Hi @fernandoj92,

The insert schema method does a very simple thing:

```Await.ready(Table.create.future(), 3.seconds)```.

You generally need 2 sets of methods:

```scala

object DatabaseService {
  def init(): Future[List[ResultSet]] = {
    val create = Future.sequence(List(
      Table1.create.future(),
      Table2.create.future()
    ))

    Await.ready(create, 5.seconds)
  }

   def cleanup(): Future[List[ResultSet]] = {
    val truncate = Future.sequence(List(
      Table1.truncate.future(),
      Table2.truncate.future()
    ))
    Await.ready(truncate, 5.seconds)
  }
}
```


Then you define your own specification, you generally don't use the default one directly.

```scala

trait CustomSpec extends CassandraFlatSpec {

   override def beforeAll(): Unit = {
     super.beforeAll()
     DatabaseService.init()
   }

   override def afterAll(): Unit = { 
     super.afterAll()
     DatabaseService.cleanup()
   }
}

```

And then you use this global spec to define the rest of your tests:

```scala

class MySpec extends CustomSpec {

  "The db service" should "insert a user into the db" in {
    ...
   }

}

```

Hope this helps.

**Comment by fernandoj92** [comment]
Thank you very much for your consideration. This helped me a lot :)
