### ISSUE TITLE
dependency issue: org.cassandraunit:cassandra-unit:2.0.2.4

### ISSUE THREAD

**Issue by kkishordn** [websudos/phantom#208]
in gradle build, I have included: com.websudos:phantom-testing_2.10:1.4.0

It started complaining about: 
Could not find org.cassandraunit:cassandra-unit:2.0.2.4 

seems 2.0.2.4 is taken out form http://maven.websudos.co.uk/list/plugins-release/org/cassandraunit/cassandra-unit/ as its no more listed there.

please suggest.

**Comment by nathanalderson** [comment]
Same problem occurs for me on a fresh clone of this repo and attempting to run `sbt test`.  In addition, if I change the dependency from cassandra-unit:2.0.2.4 to cassandra-unit:2.1.3.1, then I hit another missing dependency: com.websudos:util-testing_2.11:0.5.0.  Changing that to 0.6.10 compiles successfully, but fails a bunch of unit tests.  I don't know if the failures are related to the changes or not.

**Comment by alexflav23** [comment]
@nathanalderson Thank you for reporting this. We are aware of the issue, it's to do with our custom Maven repository having a downtime. The issue has now been fixed and all the missing dependencies are being systematically re-deployed back to Maven to restore functionality.

**Comment by kkishordn** [comment]
@alexflav23, we are still facing the issue with cassandra-unit:2.0.2.4.

**Comment by alexflav23** [comment]
@kkishordn ```cassandra-unit``` is now re-published to our Maven repository and should be back and working in the ```phantom-testkit```.

**Comment by nathanalderson** [comment]
It looks like 2.0.2.5 is available from `maven.websudos.co.uk`, but phantom still depends on 2.0.2.4, which is still unavailable.  Also, util-testing_2.11-0.5.0 is still not available.  Are we doing something wrong?

**Comment by alexflav23** [comment]
@nathanalderson We are working to publish a new cut of phantom with the 2 new dependencies and that should hopefully be available today.

In the mean time you can exclude cassandra-unit from the phantom-testkit dependency and manually add 2.0.2.5. You can also bump the util version used to 0.6.11, which is available on our Maven repo.

**Comment by alexflav23** [comment]
@nathanalderson A Phantom 1.5.0-R2 has just been published to our Maven repo to address the issues with dependency resolution. Everything should be working fine now. Please let us know if anything goes wrong.

**Comment by tosoonee** [comment]
phantom-testing_2.11-1.5.0-R2.pom also declares the dependency

         <dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit</artifactId>
            <version>2.0.2.4</version>

can you check it again?
