### ISSUE TITLE
Count(*) query return always 1

### ISSUE THREAD

**Issue by mmoulou** [websudos/phantom#209]
Hello,

I've an wrong result on my count(*) query (my query return always count=1),  after searching, i found that you set limit =1 on SelectCountWhere class.

i couldn't set limit to another value, i'm having  an IllegalStateException("A LIMIT value has already been provided")

**Comment by mmoulou** [comment]
DATASTAX Documentation: 

Counting returned rows¶

A SELECT expression using COUNT(*) returns the number of rows that matched the query. Alternatively, you can use COUNT(1) to get the same result.

Count the number of rows in the users table:

SELECT COUNT(*) FROM users;

Specifying rows returned using LIMIT¶

Using the LIMIT option, you can specify that the query limit the number of rows returned.

SELECT COUNT(*) FROM big_table LIMIT 50000;
SELECT COUNT(*) FROM big_table LIMIT 200000;

**The output of these statements if you had 105,291 rows in the database would be: 50000 and 105291**

**Comment by alexflav23** [comment]
@mmoulou Many thanks for reporting this, it is indeed a DSL error. We enforce a ```LIMIT 1``` on ```one``` and ```get``` calls for performance reasons and clarity reasons, but that works differently in a count because Cassandra will limit the results before counting them.

That means whenever you count and limit at the same time, you get at most the limit. Anyway, we will deploy a fix very shortly.

**Comment by rahulsinghai** [comment]
@mmoulou Can you please let us know how you write count(*) query in Phantom DSL? I am using version 1.5.0 and could not find any way to make count(*) a part of select query.

**Comment by alexflav23** [comment]
@rahulsinghai ```MyTable.count.one``` is the current version. In Phantom 1.6.0 and above, it will change to ```MyTable.select.count```.

**Comment by rahulsinghai** [comment]
@alexflav23 Thanks for your reply. Is there any way to count the number of rows for a `select` query with `where` clause in 1.5.0? `MyTable.count.one` will return all the rows in the table.

**Comment by alexflav23** [comment]
@rahulsinghai I suggest taking the time to familiarise yourself with phantom by reading the docs.
```MyTable.count.where(_.name eqs "Peter").and(_.age eqs 15).one()```

**Comment by alexflav23** [comment]
@mmoulou  I'm now going to close this ticket as it's been resolved in the latest development cut. We are working very hard to ensure that will go live as soon as possible.
