### ISSUE TITLE
module not found: org.cassandraunit#cassandra-unit;2.0.2.4

### ISSUE THREAD

**Issue by fernandoj92** [websudos/phantom#211]
Hi, I am having some trouble with travis because it cannot resolve that specific module. I lookedinto your Travis jobs and found that your version is the .5, but i dont know how to set mine to .5.

In your project you have your Build.scala with a 2.0.2.4 version and i think thats causing me trouble, but i am not sure.

Here the build.scala fo your project which i am referring to: 
https://github.com/websudos/phantom/blob/da1d539b04df5236730cb0d4e0d460d93d5d6df7/project/Build.scala
My Travis build with the error:
https://travis-ci.org/fernandoj92/TheraBeta/builds/55874184

**Comment by alexflav23** [comment]
@fernandoj92 Can you override that dependency with a 2.0.2.5 version of the same artefact? We have had some trouble with our Maven repository which has unfortunately caused the loss of old artefacts.

**Comment by fernandoj92** [comment]
I got these 2 errors, but it passed green, so i believe its ok:
* [error] Server access Error: Connection timed out url=http://maven.websudos.co.uk/ext-release-local/org/easytesting/fest/1.0.8/fest-1.0.8.jar
* [error] Server access Error: Connection timed out url=http://maven.websudos.co.uk/ext-release-local/net/sf/ehcache/ehcache-parent/2.5/ehcache-parent-2.5.jar

I dont know a lot about SBT, didnt know i could overwrite dependencies like that, so thank you, i just copied yours and change it.

Thank you very much for your fast response once again. Close the issue whenever you see fit.

**Comment by alexflav23** [comment]
@fernandoj92 Good to hear the issue is now resolved!
