### ISSUE TITLE
What is the correct way to use BlobColumn and ByteBuffer with Phantom?

### ISSUE THREAD

**Issue by polymorpher** [websudos/phantom#228]
Whenever I execute an insert query with a BlobColumn set to some ByteBuffer value, I get the following error:
com.datastax.driver.core.exceptions.SyntaxError: line 1:X no viable alternative at input 'Y'

where X is some arbitrary value and Y is some symbol (e.g = ) { } etc.)

Upon manual inspection of the query string, I found the query string is truncated to where I set the value of the BlobColumn in the insert statement.

It could be a problem at my end but after spending a few hours on it without any result I thought it might be wiser to ask other people.

**Comment by alexflav23** [comment]
@polymorpher Thank you for reporting this. Please confirm if you are using phantom 1.8.0 or if you are currently on an older version. It may well be that the new QueryBuilder we just launched is still not 100% stable as most things aren't in their first week after launch.

If you confirm the version I will be able to assist you further.

**Comment by polymorpher** [comment]
Yes, I am using 1.8.0.

**Comment by alexflav23** [comment]
@polymorpher I will double check that we have tests for that. If they're broken, I will release a fix within the next 2 - 3 hours to our Maven repo.

**Comment by alexflav23** [comment]
@polymorpher This was indeed an issue on our end it seems, it's now fixed and available in a PR. I will publish a 1.8.1 release for this, it should be available to you in some 15 minutes. Thank you for reporting the bug and sorry to have made you waste a few hours.

**Comment by alexflav23** [comment]
@polymorpher This is just a confirmation that 1.8.1 has landed on maven.websudos.co.uk and you should no longer have issues using BlobColumns. I will now close this ticket, please let us know if there are any further problems on your end.
