### ISSUE TITLE
Index + Primary Key column

### ISSUE THREAD

**Issue by kelvl** [websudos/phantom#239]
When trying to define a column that is part of the primary key and a secondary index, compilation fails with an `illegal inheritance` error

```
object testColumn extends StringColumn(this) with PrimaryKey[String] with Index[String]
```

**Comment by alexflav23** [comment]
@kelvl I take it the primary is part of a compound key. Compilation does indeed fail and I would say using the double indexing is at the very least a code smell. Perhaps a secondary table indexed by the other primary would be the way to go.

I will add a bug and test for this in the next version of phantom.

**Comment by kelvl** [comment]
@alexflav23 thank you for the quick response. You are right, even if it is allowed by Cassandra, it's definitely not the best way to design the indexes for the table. 

I will look into re-working the data model to prevent cases like these. Thanks again
