### ISSUE TITLE
1.8.4 missing pom in maven central

### ISSUE THREAD

**Issue by kareblak** [websudos/phantom#240]
The phantom-dsl_2.11-1.8.4 is missing its pom in the central maven repository.

ivy-1.8.4.xml                                      10-May-2015 23:37                3180
ivy-1.8.4.xml.md5                                  10-May-2015 23:37                  32
ivy-1.8.4.xml.sha1                                 10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4-javadoc.jar                 10-May-2015 23:37             1126646
phantom-dsl_2.11-1.8.4-javadoc.jar.asc             10-May-2015 23:37                 475
phantom-dsl_2.11-1.8.4-javadoc.jar.asc.md5         10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4-javadoc.jar.asc.sha1        10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4-javadoc.jar.md5             10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4-javadoc.jar.sha1            10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4-sources.jar                 10-May-2015 23:37              102934
phantom-dsl_2.11-1.8.4-sources.jar.asc             10-May-2015 23:37                 475
phantom-dsl_2.11-1.8.4-sources.jar.asc.md5         10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4-sources.jar.asc.sha1        10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4-sources.jar.md5             10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4-sources.jar.sha1            10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4.jar                         10-May-2015 23:37              667751
phantom-dsl_2.11-1.8.4.jar.asc                     10-May-2015 23:37                 475
phantom-dsl_2.11-1.8.4.jar.asc.md5                 10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4.jar.asc.sha1                10-May-2015 23:37                  40
phantom-dsl_2.11-1.8.4.jar.md5                     10-May-2015 23:37                  32
phantom-dsl_2.11-1.8.4.jar.sha1                    10-May-2015 23:37                  40

**Comment by alexflav23** [comment]
@kareblak We have noticed the mistake yesterday, although there is still an ongoing investigation as to why this would ever happen. We will keep you up-to-date as soon as a fix is deployed.

**Comment by foovungle** [comment]
+1

**Comment by alexflav23** [comment]
@kareblak This was a weird issue around using the bintray SBT plugin. Phantom 1.8.6 has now been published to bintray to fix this. Hope that will work well from now on!

**Comment by foovungle** [comment]
How long does it take to propogate? I only see 1.8.3 on bintray.

```$ curl https://dl.bintray.com/websudos/oss-releases/com.websudos/phantom-dsl_2.11/
...
<body>
<pre><a onclick="navi(event)" href="#1.8.3/" rel="nofollow">1.8.3/</a></pre>
</body>
```

**Comment by alexflav23** [comment]
Hi @foovungle,

I have hit the publish button and the version is showing as available in the main interface. The badge I have added to the README also points to 1.8.6, so I'm quite surprised this is still a problem.

Regards,

**Comment by foovungle** [comment]
Adding `  "Websudos bintray" at "https://dl.bintray.com/websudos/oss-releases"` to the `resolvers` does work now. Thanks for your help.

**Comment by alexflav23** [comment]
@foovungle That's great, we also have a working build on Travis using the new bintray based resolver so everything should be fine from now on!
