### ISSUE TITLE
Your docs don't describe how to use the library

### ISSUE THREAD

**Issue by lostinplace** [websudos/phantom#241]
At no point in your tutorials section is there a series of steps that can be used to accomplish a task using phantom.

**Comment by alexflav23** [comment]
Hi @lostinplace,

Thank you for your feedback, we have to admit it's the very first of it's kind. The documentation is indeed very detailed about anything you should know about phantom, features an example module and a significant number of examples in the test module.

I can only take you are extremely new to Scala and development in general, in which case perhaps Scala resources and general introductions to the JVM world may be far more beneficial than spending time posting unwarranted comments. Time will tell I suppose. 

Regards,

**Comment by lostinplace** [comment]
I gather that I offended you in some way.  Sure, I'll buy that.

I'm pretty new to scala, but a quick web search informs me that I have in
fact been writing software since you were literally in diapers.

I was (and still am) interested in using your library for a project, but at
no point in your repo's documentation do you actually specify a workflow.
Please note that this is common practice that your dependencies all honor
(I'm going to refer to spark-cassandra-connector but I imagine that you are
capable of googling your own peer projects for yourself)

-Chris
