### ISSUE TITLE
Cannot use phantom 1.8.x in scala 2.11 project

### ISSUE THREAD

**Issue by voidcontext** [websudos/phantom#246]
At first I tried to use phantom-dsl 1.8.4, but sbt couldn't find its pom file in the central maven repo. The lib is there, but the pom file is missing.

After that I tried to use version 1.8.0, but sbt couldn't resolve these dependencies:

- com.websudos#util-zookeeper_2.11;0.6.12
- com.websudos#util-testing_2.11;0.6.12
- org.cassandraunit#cassandra-unit;2.0.2.5

I think this happens because the Websudo's maven repository is down.

**Comment by alexflav23** [comment]
Hi @voidcontext,

The Websudos maven repo is now deprecated and permanently out of service. Instead, add this to your resolvers:

```scala

resolvers ++= Seq(
  Resolver.bintrayRepo("websudos", "oss-releases")
)
```

We are now deploying all new releases to bintray and Maven Central instead of the Websudos Maven repo.

**Comment by voidcontext** [comment]
Thank you for the prompt reply.

However I'm still unable to get it to work. 

Sbt cannot resolve phantom-dsl 1.8.4.
```
[warn]  module not found: com.websudos#phantom-dsl_2.11;1.8.4
[warn] ==== local: tried
[warn]   /home/pgee/.ivy2/local/com.websudos/phantom-dsl_2.11/1.8.4/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/websudos/phantom-dsl_2.11/1.8.4/phantom-dsl_2.11-1.8.4.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.websudos/phantom-dsl_2.11/1.8.4/ivys/ivy.xml
[warn] ==== bintray-websudos-oss-releases: tried
[warn]   https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-dsl_2.11/1.8.4/phantom-dsl_2.11-1.8.4.pom
```

When I'm trying to user version 1.8.0 I get the following:

```
[warn]  module not found: com.websudos#util-zookeeper_2.11;0.6.12
[warn] ==== local: tried
[warn]   /home/pgee/.ivy2/local/com.websudos/util-zookeeper_2.11/0.6.12/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/websudos/util-zookeeper_2.11/0.6.12/util-zookeeper_2.11-0.6.12.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.websudos/util-zookeeper_2.11/0.6.12/ivys/ivy.xml
[warn] ==== bintray-websudos-oss-releases: tried
[warn]   https://dl.bintray.com/websudos/oss-releases/com/websudos/util-zookeeper_2.11/0.6.12/util-zookeeper_2.11-0.6.12.pom
[info] Resolving com.websudos#util-testing_2.11;0.6.12 ...
[warn]  module not found: com.websudos#util-testing_2.11;0.6.12
[warn] ==== local: tried
[warn]   /home/pgee/.ivy2/local/com.websudos/util-testing_2.11/0.6.12/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/websudos/util-testing_2.11/0.6.12/util-testing_2.11-0.6.12.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.websudos/util-testing_2.11/0.6.12/ivys/ivy.xml
[warn] ==== bintray-websudos-oss-releases: tried
[warn]   https://dl.bintray.com/websudos/oss-releases/com/websudos/util-testing_2.11/0.6.12/util-testing_2.11-0.6.12.pom
```

I have these resolvers:

```scala
      resolvers ++= Seq(
        Classpaths.typesafeReleases,
        Resolver.bintrayRepo("websudos", "oss-releases"),
        "Twitter Repository" at "http://maven.twttr.com"
      ),
```

**Comment by alexflav23** [comment]
Hi @voidcontext,

Try the latest release pushed to Bintray, which is 1.8.6. That should be available and working as expected. Apologies for the service interruption.

Regards.

**Comment by santoshv98** [comment]
@alexflav23
I tired with the same setup as you have mentioned(Resolver.bintrayRepo)  and it couldnt resolve scalatra depedency (phantom-test) . Did it make it to bintrayRepo?

**Comment by alexflav23** [comment]
@santoshv98 It did and the Travis build also works, which means dependency resolution is fine. Perhaps retry that. Scalatra is not a direct dependency, it is used in `phantom-scalatra-test` which is not intended for usage beyond the test module.

I don't think phantom is the one causing this issue and if you are directly depending on scalatra-test remove that as it's not really doing anything for you.

**Comment by juanjovazquez** [comment]
Same problem here. Unable to resolve dependencies with bintray resolver configured.

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.websudos#phantom-dsl_2.11;1.8.6: not found
[warn] 	:: com.websudos#phantom-testkit_2.11;1.8.6: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.websudos:phantom-dsl_2.11:1.8.6 (/data/sources/tecsisa/git/reactive-cassandra/build.sbt#L21)
[warn] 		  +- com.tecsisa.wr:reactive-cassandra_2.11:0.0.1-SNAPSHOT
[warn] 		com.websudos:phantom-testkit_2.11:1.8.6 (/data/sources/tecsisa/git/reactive-cassandra/build.sbt#L21)
[warn] 		  +- com.tecsisa.wr:reactive-cassandra_2.11:0.0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.websudos#phantom-dsl_2.11;1.8.6: not found

**Comment by alexflav23** [comment]
@juanjovazquez We are still not sure how that can happen given it's working perfectly fine in our own infrastructure and even beyond in Jenkins, Travis, and other CI tools + a variety of projects. We will publish a fix version to Maven Central today to avoid further problems.

Apologies for the service interruption.

**Comment by juanjovazquez** [comment]
I could already get all dependencies. Thanks!.

**Comment by voidcontext** [comment]
Hi @alexflav23,

I was able to fetch all needed dependencies from the Bintray repo when I used version 1.8.6.

Thank you for your help.
