### ISSUE TITLE
Escaping single quotes in unlogged batch statements broken in 1.8.6

### ISSUE THREAD

**Issue by brianwawok** [websudos/phantom#247]
I have 2 very simple tables with two fields.. 

create table foo(
  a varchar primary key,
  b varchar
)

create table foo2(
  b varchar primary key,
  a varchar
)

I am storing long auto-generated strings. If the string generated has no single quote, life is good. If it DOES have a single quote.. it breaks.

I am using an unlogged batch.

I see something like this in the debugs..

```
 BATCH DELETE FROM foo WHERE a= 'AroIeEPofsUKiTzT2M1!mADHQ(qV)xw~xyM6Nzd98Y_kMJHj*2d5lp4Ey'HMcRM'; DELETE FROM foo2 WHERE a = 'username@email.com'; APPLY BATCH;
```

You can see the problem.. the ' mark before the HMc in the statement...

Did not see this in 1.5, so I suspect something is wrong with batch statement escaping in 1.8?

**Comment by alexflav23** [comment]
@brianwawok The escape mechanism has indeed changed and will be updated to fix this as well. Many thanks for reporting it!

**Comment by brianwawok** [comment]
I think this also may expose some query injection risk, making this pretty bad.

**Comment by alexflav23** [comment]
@brianwawok This has been fixed in the latest version that will make Bintray shortly. We will let you know once that has happened.

Regards.
