### ISSUE TITLE
How do I do Objects inside Objects?

### ISSUE THREAD

**Issue by santoshv98** [websudos/phantom#248]
@alexflav23 

1. If I have a case class with this kind of structure (like we do in the ORM world), how do I create the columns in CassandraTables subclasses?

case class A(s: String, b: TokenInfo)
case class TokenInfo(email: String, issuedTime: DateTime, issuer: String, expirationDate: DateTime, customToken: String) {

````class As extends CassandraTable[As, A]....

2. Would I have to create the boilerplate (CassandraTable subclasses, Objects, Columns inside subclasses and the row method) for all the case classes? May be we should work on simplyfying this(dont know at this time how though) - could we just create a case class and make all the plumbing happens behind the scenes?

3. If I have columns that are nullable - do I have to declare my case classes to depict such a scenario?

**Comment by alexflav23** [comment]
Hi @santoshv98 ,

Please review the documentation which adequately addresses all your questions. The tests inside phantom-dsl will also be a really useful resource. Issues are mainly used for bug reports and feature requests.

Regards,
