### ISSUE TITLE
1.8.6 went too far on secondary index fix

### ISSUE THREAD

**Issue by brianwawok** [websudos/phantom#249]
Your driver allows a delete by secondary index where clause, but cassandra does not.

In issue https://github.com/websudos/phantom/issues/232

I think maybe the compile time checks were scaled back too far

http://stackoverflow.com/questions/27484821/cassandra-delete-using-clustering-column-or-secondary-index-not-working

i.e. this will compile, but then blow up in the database

```
sealed class Foos extends CassandraTable[Foos, Foo] with DBConnector {

  object a extends StringColumn(this) with PartitionKey[String]

  object b extends StringColumn(this) with Index[String]

  def blowUpDelete(b : String) = {
     delete
     .where(_.b eqs b)
     .future()
}
```

**Comment by alexflav23** [comment]
Hi @brianwawok,

This is indeed true, I don't think the driver has the means to distinguish between unindexable and undeletable just yet, we just went by the assumption that the two will always overlap, not the case as it stands.

A fix will be available for this in the next major release, many thanks for reporting it!

Regards.

**Comment by brianwawok** [comment]
@alexflav23 it is pretty dumb you can search by secondary index but not delete by it, maybe it will be fixed in the feature by Cassandra...

**Comment by alexflav23** [comment]
Hi @brianwawok,

It is indeed unpleasant, however it's not by accident. Secondary indexes are not a technical reality in Cassandra and I have very little doubt this was something done by popular demand at the best of sales procedures. Bills need to be paid for, and there is an unfortunate truth in that at times, however the way secondary indexes are made possible also makes it impossible to do deletes.

There are a variety of race conditions that could easily break the tombstone model Cassandra uses for deletes and determining a "winner", establishing consistency, eliminating zombies and so on is enough of a challenge in Cassandra as it is. This is better explained in the Cassandra Jira [here](https://issues.apache.org/jira/browse/CASSANDRA-5527).

Generally speaking, any feature that looks weird in Cassandra is generally like that as it was dumbed down for ease of use reasons.

Regards,
Flavian

**Comment by alexflav23** [comment]
Hi @brianwawok,

We cannot really apply a DSL level fix to this without very major alterations to the existing internals and implicit mechanism and the benefit is rather minimal. All the damage executing that query will do is a runtime error, after which the user can correct the mistake anyway, so it's not something as bad as a limit on a Mongo delete query(limit is ignored and Mongo happily proceeds deleting the entire collection without any warning or error message, or such was the case a few years back).

Regards.

**Comment by brianwawok** [comment]
@alexflav23 true, but isn't there whole point of having a Cassandra DSL to catch things at compiletime over runtime?  Or we would all just be slinging ruby.

**Comment by alexflav23** [comment]
@brianwawok The current model phantom employs makes it somewhat difficult to implement this without potential heavy changes so we just mark it as a reasonable trade-off. This will be addressed later in the future when we solve other high priorities issues.
