### ISSUE TITLE
Connect phantom to non-standard port

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#257]
Hi,
I'm tring to configure phantom to connect to cassandra on different port. I have tried to use the following code
```

object CassandraManager extends DefaultCassandraManager {

  override val hosts = Set(
    new InetSocketAddress("127.0.0.1", 2222)
  )
}

trait DatabaseConnector extends SimpleCassandraConnector {
  implicit val keySpace = KeySpace("some-keyspace")
  override val manager = CassandraManager
}
```

but result is it is just throwing
>   com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))

Exception does not even mentioned my host.

**Comment by alexflav23** [comment]
Hi @mmatloka,

That's very strange. Try version `1.9.1`, although it does come with some changes to the connectors API.

```scala

trait KeySpaceDef {
  implicit val space: KeySpace = KeySpace("app")
}

object Defaults extends KeySpaceDef {
  val connector = ContactPoints(Seq("127.0.0.1"), 2022).keySpace(space.name)
}

trait Connector extends Defaults.connector.Connector with KeySpaceDef
```

**Comment by mmatloka** [comment]
Under `1.9.1` it works :)

**Comment by alexflav23** [comment]
@mmatloka Great news, I've just published the latest util to Bintray and I take it it's already propagated! The documentation and official release of the 1.9 series will follow later in the week, but meanwhile you can use this.
