### ISSUE TITLE
Schema migration/drop

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#258]
Hi, 
I am trying to update my schema via phantom. When I execute `automigrate`on table result is all my columns beside `id` column are removed, and no columns are re-added. Is there any way to manually drop table using phantom-dsl?

**Comment by alexflav23** [comment]
Hi @mmatloka,

Automigration is not yet live and that's why it hasn't been advertised. It was merged in along with a big changeset but aside from that you shouldn't rely on it just yet.

You can run an arbitrary query within the session if you want.

```scala

blocking {
  session.execute(s"DROP TABLE ${keySpace.name}.$tableName")
}

```


Regards.
