### ISSUE TITLE
OptionalTimeUUID column is missing

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#260]
Hi,
Readme (https://github.com/websudos/phantom#optional-primitive-columns ) specifies its possible to create a column of type `OptionalTimeUUID` but it is not present in code https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/dsl/package.scala#L95 .

Phantom dsl version `1.9.1`

**Comment by alexflav23** [comment]
Hi @mmatloka,

Thank you for reporting this, you can help out with a pull request!

Regards.

**Comment by mmatloka** [comment]
@alexflav23 I see that develop is tagged with `1.8.12` and `1.9.1` is only on release branch (not merged back to develop yet). So to create PR based on which branch? ;)

**Comment by alexflav23** [comment]
Hi @mmatloka,

1.9.1 has now been merged in and you can send a pull request against that.

Many thanks!

Regards.
