### ISSUE TITLE
CassandraPrimitive, select.where on OptionalStringColumn 

### ISSUE THREAD

**Issue by borut123** [websudos/phantom#261]
I'm trying to do select.where by OptionalStringColumn in phantom 1.8.12.

In phantom 1.5.x it was something like this, but now CassandraPrimitive class does not exist any more.
implicit object OptionStringIsCassandraPrimitive extends CassandraPrimitive[Option[String]] {
    val cassandraType = "Option[String]"
    def cls: Class[_] = classOf[Option[String]]
    def fromRow(row: Row, name: String): Option[Option[String]] =
      Some(Try(row.getString(name)).toOption)
  }

**Comment by alexflav23** [comment]
Hi @borut123, Indexes are not optional so you cannot have an optional index. This is not an accident in the DSL, but a modelling error in your app that you should fix. Create a separate table or similar for the new query and that should fix everything.
