### ISSUE TITLE
Dependency resolution errors

### ISSUE THREAD

**Issue by melodious** [websudos/phantom#263]
I am unable to reach download the twitter-finagle dependency and am getting the following error:
```
[error] Server access Error: Connection timed out url=http://maven.websudos.co.uk/ext-release-local/com/twitter/finagle-zookeeper_2.11/6.24.0/finagle-zookeeper_2.11-6.24.0.pom
```

**Comment by alexflav23** [comment]
Hi @melodious,

Please read the README as Maven Websudos is no longer available. All our artefacts are now available via Bintray.

Regards.

**Comment by melodious** [comment]
Thanks for the quick reply. I missed that since the websudos is still listed under the section "Integrating phantom in your project"
