### ISSUE TITLE
Secondary index on collection type column

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#264]
Hi,
Is it possible to use with phantom secondary indexes e.g. on set type columns? In cassandra its theoretically possible http://www.datastax.com/dev/blog/cql-in-2-1 but code
` extends SetColumn[SomeTable, SomeEntity, String](this) with Index[String]` does not compile.

**Comment by alexflav23** [comment]
Hi @mmatloka,

We will add this as a bug if it is indeed the case. The current roadmap features support for `CONTAINS` and `CONTAINS KEY` but this would be a good addition. The modelling you are pulling off here sounds like a smell from a distance though.

Regards.

**Comment by mmatloka** [comment]
Well, in some specific cases a collection type column with index seems to be a nice alternative for fully denormalized modelling of relations.

**Comment by alexflav23** [comment]
@mmatloka Could you elaborate on those cases? Would be great to understand the exact scenarios when making the DSL changes. I have some many to many ideas in mind for this kind of approach, but it's best we are on the same page.

**Comment by mmatloka** [comment]
Simple example. M:N relation and the query is to get all entries of type A related to 'id' of entries of type B. So in this case you can denormalize, and have a row, containing all columns of A, and `id' of B (so its like table A_by_B_id), when you query, you filter by this id and get a list of rows. However if there is one entry of type A, and 10 related type B, then data of type A is duplicated 10 times.

With set column, ids of type B can be kept in one columnt of type A. So then you query the table, wanting to get those entries, where ids column contains my id. There is no denormalization needed here. However drawback is that the whole entry will be fetched with all ids (in CQL3.1 limit of collection type column is 2 bilions entires or sth like that).

From DSL perspective it would be nice just to be able to` select.where(_.ids contains id).fetch()` where `ids` is a `SetColumn` :)

**Comment by alexflav23** [comment]
Hi @mmatloka,

I take your point. It seems this functionality was already on the roadmap in the backlog of our Jira and that it will be done quite shortly according to schedule, which should be within the next few days.

Regards.

**Comment by alexflav23** [comment]
Hi @mmatloka ,

1.9.3 is now on Bintray, it will be shortly available on GitHub after we sort out discrepancies with the Travis Cassandra version. When you use an `Index`, make sure to specify the full type held in a column, including the relevant Scala collection. Have a look below.

```scala
  object setText extends SetColumn[IndexedCollectionsTable, TestRow, String](this) with Index[Set[String]]

  object mapTextToText extends MapColumn[IndexedCollectionsTable, TestRow, String, String](this) with Index[Map[String, String]]
```

As a last detail, Cassandra supports indexes on map keys and using `CONTAINS KEY`, but we haven't yet added that, so only the default `CONTAINS` for values is implemented.

**Comment by mmatloka** [comment]
Confirmed working on our side :) thx!

**Comment by alexflav23** [comment]
Hi @mmatloka, support for `CONTAINS KEY` has been added today as well. We will release a new version shortly to include that. It's done by mixing one more trait, like this:

```
object mapIntToText extends MapColumn[IndexedCollectionsTable, TestRow, Int, String](this) with Index[Map[Int, String]] with Keys

```
