### ISSUE TITLE
Spray and Shapeless incompatible versions

### ISSUE THREAD

**Issue by thiagoandrade6** [websudos/phantom#267]
I saw you have been using the shapeless 2.2.0-RC4 and unfortunately this is incompatible with the latest shapeless library that spray are using.

To be clear, I'm saying this is a bug, incompatible versions can occur any time.

There is already a opened issue for this:

[https://github.com/spray/spray/issues/1051](https://github.com/spray/spray/issues/1051)

The question is... do you have any version where you do use a shapeless library 2.1 or any compatible with spray, according to this link:

[http://spray.io/project-info/current-versions/#shapeless-versions](http://spray.io/project-info/current-versions/#shapeless-versions)

Apparently the old 1.5.0 version does not use shapeless, at least I couldn't find any reference to it.

Using the 1.9.3 or the 1.8.12 causes an incompatible version error and some part of the spray code stop compiling.

**Comment by alexflav23** [comment]
Hi @thiagoandrade6,

We will try and upgrade to the new shapeless shortly. In theory, it shouldn't be a huge problem on our end to bump shapeless versions but things may well go wrong rather easily.

This will be done some time this week and you can expect to see it on Bintray shortly. This issue will be updated once the incompatibility issue is resolved.

Regards.

**Comment by thiagoandrade6** [comment]
Thank you @alexflav23 and indeed, using the Spray shapeless version, worked fine.

**Comment by maniteja6799** [comment]
Hi, I am facing the same issue, not working even if i excluded shapeless as suggested above, is there any alternative for this?

**Comment by alexflav23** [comment]
https://github.com/outworkers/phantom/wiki/Integrating-phantom-in-your-project#using-phantom-with-the-spray-framework

**Comment by maniteja6799** [comment]
Thanks @alexflav23
