### ISSUE TITLE
v1.9.1 - Use of EnumColum in a query condition

### ISSUE THREAD

**Issue by javdom-tecsisa** [websudos/phantom#268]
Hi,

  I'm trying to create a query which filters through the value of an EnumColum. As far as I could see, when I try to compare the column with another enum it shows an error... I think its due to the library doesn't contains the necessary implicit to make the conversion for the eqs.

The provisional solution I could find it's compare the EnumColumn through its ID, having to store the ID instead of the enum string... The question is, there is any way to compare by enums instead using the ID?

... This is what I would like to do ...
select.where(_.enum_col eqs EnumObject)

Thanks in advance

**Comment by alexflav23** [comment]
Hi @javdom-tecsisa,

Enum columns cannot automatically be converted to primitives because conversion requires a host object. That's why you have to define your own primitive and import it into the right scope, like this:

```scala

implicit val enumPrimitive: Primitive[MyEnum#Value] = enumToQueryConditionPrimitive(MyEnum)

```
