### ISSUE TITLE
1.8.12 SetColumn, ListColumn, MapColumn do not support static column?

### ISSUE THREAD

**Issue by lizepeng** [websudos/phantom#269]
Hello everyone

I recently upgraded phantom to 1.8.12 from 1.5.0, but automated create table dsl generation seems to be broken. 

In both 1.8.12 and develop branch, 
PrimitiveColumn and OptionalPrimitiveColumn do have these logic for static column,
```scala
  override def qb: CQLQuery = {
    val root = CQLQuery(name).forcePad.append(cassandraType)

    if (isStaticColumn) {
      root.forcePad.append(CQLSyntax.static)
    } else {
      root
    }
  }
```
but for SetColumn, ListColumn and MapColumn, there are not such logic.

In my opinion, static collection column should be allowed, because
```cql
CREATE TABLE my_table (
  id timeuuid,
  name text,
  attributes map<text, text> STATIC,
  child_id uuid,
  PRIMARY KEY (id, name)
);
```
works under cqlsh in my dev environment.

so, Is this a bug or did I misunderstand something?

**Comment by alexflav23** [comment]
@lizepeng You should be able to easily use statics with collections, I don't understand what the problem is and why you care about the internals. Here's a simple example:

```scala

object staticList extends ListColumn[StaticCollectionTableTest, StaticCollectionRecord, String](this) with StaticColumn[List[String]]

```

**Comment by lizepeng** [comment]
@alexflav23 thank you for your reply
Because without those if statements, phantom could not generate correct cql for creating table with static collection column.

I can only get this cql from phantom 1.8.12
```cql
CREATE TABLE my_table (
  id timeuuid,
  name text,
  attributes map<text, text>,
  child_id uuid,
  PRIMARY KEY (id, name)
);
```
but what I want is
```cql
CREATE TABLE my_table (
  id timeuuid,
  name text,
  attributes map<text, text> STATIC,
  child_id uuid,
  PRIMARY KEY (id, name)
);
```

**Comment by alexflav23** [comment]
Hi @lizepeng,

Try 1.9.5, I've added tests for static collections [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/db/specialized/StaticColumnTest.scala). Hope this helps.
