### ISSUE TITLE
Delete ... if ...

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#270]
Hi,
Is it curently possible to execute in phantom dsl such type of query:
`delete from someTable where id = 89dfbe10-0f45-11e5-99a4-d43d7ebcc606 if someSet= {};` ? :) (cassandra allows for such query even without index on set column).

**Comment by alexflav23** [comment]
Hi @mmatloka,

That's not by accident. The compare and set clause must be matched against a non-primary column, so I think that behaviour is correct according to Cassandra spec. You match with the `where` clause and you can actually never have an `is` on a column that's indexed.

I don't think `DELETE .. IF` is yet part of the mix and I'm not 100% sure Cassandra even supports this, we will have to double check.

Regards.

**Comment by alexflav23** [comment]
Hi @mmatloka,

There is indeed a `DELETE IF` in Cassandra, something we missed in the original implementation of Lightweight and compare and set. Regardless, it will be added to the pipeline.

Regards.

**Comment by mmatloka** [comment]
Hi @alexflav23 ,
Sorry, I have made a mistake in description, I meant from the beggining that Cassandra allows for that, but I have written 'Phantom' instead ;/. 

> Regardless, it will be added to the pipeline.

:+1:

**Comment by alexflav23** [comment]
@mmatloka This is now fixed in 1.9.7.
