### ISSUE TITLE
1.8.12 eqs operator does not work with onlyIf(...)

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#273]
but Cassandra clearly still allows this operation.

Table:
```scala
sealed class PartitionTable extends CassandraTable[PartitionTable, Partition] {
  // scalastyle:off
  object dataset extends StringColumn(this) with PartitionKey[String]
  object partition extends StringColumn(this) with PartitionKey[String]
  object hash extends IntColumn(this)
```

Query:
```scala
    update.where(_.dataset eqs newPart.dataset).and(_.partition eqs newPart.partition)
          .modify(_.hash setTo newPart.hashCode)
          .onlyIf(_.hash eqs partition.hashCode)
```

does not compile:
```
value eqs is not a member of object x$14.hash
[error]           .onlyIf(_.hash eqs partition.hashCode)
```

**Comment by alexflav23** [comment]
Hi @velvia,

In versions 1.8.x and above we completely replaced the old implicit mechanism to simplify things and the naming of `eqs` was changed to `is` to prevent obscure compilation messages that you were getting in the past for misusing indexes.

Regards.

**Comment by velvia** [comment]
Ok can you please update the documentation / wiki?  It still says eqs. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead
