### ISSUE TITLE
ResultSet information

### ISSUE THREAD

**Issue by fernandoj92** [websudos/phantom#275]
Well, this is more of a Datastax driver question i think, but maybe you can help me.

Is there a way of knowing if an instertion, update, etc has been succesful? I am new to Scala and i cannot fin a way to transform a Future[ResultSet] into a Future[Boolean]

Thank You

**Comment by alexflav23** [comment]
Hi @fernandoj92,

Yes, basically when you don't select, phantom returns a Datastax `ResultSet`, which has a `wasApplied` method. I'm not 100% if the method in question is 100% reliable or is meant to always give you the appropriate result, yet this is how to go about it:

```scala

val query = Table.update.where(_.id eqs "test").modify(_.a setTo "b").future()

query map {
  res => res.wasApplied()
}


```

**Comment by fernandoj92** [comment]
Thank you very much, will try this now.
