### ISSUE TITLE
Bugs with ByteBuffer/Blob handling in 1.8.x

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#276]
Phantom does not properly handle the following ByteBuffer conditions on write for Blob types in 1.8.x:

* When the ByteBuffer position is nonzero, or
* When the ByteBuffer position is zero, but the `arrayOffset` is nonzero.
* When the ByteBuffer is direct allocated

This can be plainly seen in the code, in Primitives.scala, where the entire backing array of the byte buffer is used for serialization -- which only works for the simple case.

I would be happy to submit a pull request, but I noticed the 1.9.x codebase is substantially different, so not sure what the authors recommend.   A fix would still make Blob writes workable for folks not ready to move to 1.9.x, so I still think it has value.

**Comment by alexflav23** [comment]
Hi @velvia ,

Many thanks for reporting this. If you address the problem in isolation, even in a Github Gist, we can retrofit the fix to all versions of phantom and retag some 1.8 releases for you. I would strongly suggest upgrading to the 1.9.x series as we've fixed a whole lot of things since, but otherwise a new 1.8.x release is possible.

Regards.

**Comment by velvia** [comment]
I just realized you guys don't have a branch for 1.8, so maybe Gist is the
way to go. Otherwise could submit a PR....

On Fri, Jun 26, 2015 at 6:50 AM, Flavian Alexandru <notifications@github.com
> wrote:

> Hi @velvia <https://github.com/velvia> ,
>
> Many thanks for reporting this. If you address the problem in isolation,
> even in a Github Gist, we can retrofit the fix to all versions of phantom
> and retag some 1.8 releases for you. I would strongly suggest upgrading to
> the 1.9.x series as we've fixed a whole lot of things since, but otherwise
> a new 1.8.x release is possible.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websudos/phantom/issues/276#issuecomment-115697326>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by velvia** [comment]
Hey guys, here is the PR.  Enjoy!

https://gist.github.com/velvia/909408dc6f053d6934be

On Sat, Jun 27, 2015 at 10:47 PM, Evan Chan <velvia@gmail.com> wrote:

> I just realized you guys don't have a branch for 1.8, so maybe Gist is the
> way to go. Otherwise could submit a PR....
>
> On Fri, Jun 26, 2015 at 6:50 AM, Flavian Alexandru <
> notifications@github.com> wrote:
>
>> Hi @velvia <https://github.com/velvia> ,
>>
>> Many thanks for reporting this. If you address the problem in isolation,
>> even in a Github Gist, we can retrofit the fix to all versions of phantom
>> and retag some 1.8 releases for you. I would strongly suggest upgrading to
>> the 1.9.x series as we've fixed a whole lot of things since, but otherwise
>> a new 1.8.x release is possible.
>>
>> Regards.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/websudos/phantom/issues/276#issuecomment-115697326>.
>>
>
>
>
> --
> If you are free, you need to free somebody else.
> If you have some power, then your job is to empower somebody else.
>    --- Toni Morrison
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by alexflav23** [comment]
Hi @velvia ,

Many thanks for fixing this. I will add you to the contributors list if you aren't already there!

I will try and get a new release out today for both 1.8.x and 1.9.x to include your fix.

Regards.

**Comment by velvia** [comment]
Many thanks for the prompt response!!

On Mon, Jun 29, 2015 at 5:19 AM, Flavian Alexandru <notifications@github.com
> wrote:

> Hi @velvia <https://github.com/velvia> ,
>
> Many thanks for fixing this. I will add you to the contributors list if
> you aren't already there!
>
> I will try and get a new release out today for both 1.8.x and 1.9.x to
> include your fix.
>
> Regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/websudos/phantom/issues/276#issuecomment-116633160>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by alexflav23** [comment]
Hi @velvia ,

Many thanks for your fix once again. It has now been included in the `1.9.9` release already available on Bintray. Have you upgraded or does this still require retrofitting to previous versions?

Regards.

**Comment by velvia** [comment]
I haven't upgraded yet.  Will have to try it out, but the 1.5 to 1.8 was already a bunch of effort.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment]
So in other words if u could back port that would be awesome (esp since the patch is against 1.8.x and should be really easy :)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by alexflav23** [comment]
Hi @velvia,

I wanted to ask if you think this would still be a requirement. Phantom has evolved quite a lot since the 1.8.x releases and many more months of improvements have been released since. Perhaps our efforts are much better spent improving the speed of upgrading and the documentation for upgrading to the latest version.

I was considering scheduling the upgrade today for the upcoming sprint but before I do so it would be useful to know if it's still needed.

Regards.

**Comment by velvia** [comment]
@alexflav23 nope you guys don't need to backport, thanks for asking though!   However, there are still some issues with the bytebuffer stuff even after the patch.  I haven't had time to dig into it, but will let you guys know.  Perhaps when the prepared statement stuff comes in (is it in already?) will make a bigger effort at upgrading and trying everything out.

Would be happy to link my project to this one and mention it too  :)

**Comment by alexflav23** [comment]
@velvia It's in the making and getting there, but not out yet. Unfortunately non trivial to do type-safe prepared statements and we have prioritised automated migrations first, but they are in prime time. We would love to know where else phantom is being used, please feel free to contribute with that or even tell me here and I will add it to the list with the appropriate credits.
