### ISSUE TITLE
CREATE TYPE support

### ISSUE THREAD

**Issue by Tvaroh** [websudos/phantom#279]
Hi, @alexflav23.

Does Phantom has `CREATE TYPE` support? Can it generate types from DSL? Or can I create a table with user-defined types and make it work with Phantom?

**Comment by Tvaroh** [comment]
Just found phantom-udt as a separate module. Probably, this is the way to go.

**Comment by Tvaroh** [comment]
Still do not understand how to use `UDTColumn`s.

```scala
case class Fullname(firstname: String, lastname: String)

object fullname extends UDTColumn[CVs, CV, Fullname](this) {
  override def asCql(v: UDTColumn[CVs, CV, Fullname]): String = ???
}
```

Why `asCql` method (which is required to implement) argument is `UDTColumn`? Shouldn't it be just my UDT i.e. `Fullname`?

**Comment by alexflav23** [comment]
Hi @Tvaroh ,

UDT support is not officially out yet, it has been in the making for a while and de-prioritised while internally we focus on a number of different projects as well. It should be live sometime around September.

Regards.
