### ISSUE TITLE
phantom-testkit: Not able to deploy auto embedded cassandra

### ISSUE THREAD

**Issue by rohitgupta-90** [websudos/phantom#284]
Hi, 

I am trying to run the example given here: https://github.com/websudos/phantom/wiki/Testing-with-phantom-teskit  with version 1.9.8  and I get the following error: 
[info] Exception encountered when attempting to run a suite with class name: UserDatabaseServiceTest *** ABORTED ***
[info]   com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
[info]   at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
[info]   at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
[info]   at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1230)
[info]   at com.datastax.driver.core.Cluster.init(Cluster.java:157)
[info]   at com.datastax.driver.core.Cluster.connect(Cluster.java:245)
[info]   at com.websudos.phantom.connectors.DefaultSessionProvider.createSession(DefaultSessionProvider.scala:52)
[info]   at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
[info]   at com.websudos.phantom.connectors.DefaultSessionProvider$$anonfun$getSession$1.apply(DefaultSessionProvider.scala:57)
[info]   at com.websudos.phantom.connectors.Cache$Lazy.get$lzycompute(DefaultSessionProvider.scala:77)
[info]   at com.websudos.phantom.connectors.Cache$Lazy.get(DefaultSessionProvider.scala:77)

The document says that an embedded cassandra node will be deployed when I run sbt run but from the error it looks like its not happening. 
FWIW, when I bring up a local node up manually and run the test, it passes.

Am I missing something here?

**Comment by alexflav23** [comment]
Hi @rohitgupta-90 ,

We have removed support for auto embedding via SBT due to severe problems with race conditions in test runs. Multiple classloaders, multiple JVMs and multiple parallel test executors don't seem to like each other as well as we need to for the kind of await lock starting Cassandra requires.

The `phantom-sbt` module is now the way forward, and documentation will be updated to reflect that shortly.
