### ISSUE TITLE
Spray 1.2.4 and phantom 1.9.8 have conflicts using shapeless

### ISSUE THREAD

**Issue by anujag231** [websudos/phantom#285]
We are trying to use phantom 1.9.8 in one of our projects which already uses spray routing (1.2.4). Our observation is the code which uses phantom fails with 

[error] bad symbolic reference. A signature in ImplicitMechanism.class refers to term shapeless
[error] in package <root> which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling ImplicitMechanism.class.
[error] bad symbolic reference. A signature in ImplicitMechanism.class refers to term package
[error] in value shapeless which is not available.

We did follow one of your other threads and excluded the shapeless as below, but that did not help.
val phantomDSL = "com.websudos" %% "phantom-dsl" % "1.9.8" exclude ("com.chuusai", "shapeless_2.10")

Any idea how to get away from this ? Is is ok to expect phantom to work with lower version of shapeless ?

**Comment by jtjeferreira** [comment]
we are using this "io.spray" %%  "spray-routing-shapeless2" % SprayVersion

**Comment by alexflav23** [comment]
Hi @jtjeferreira , @anujag231 ,

I've added your comment to the Wiki page on how to include phantom. All future users will now know how to deal with this easily. Many thanks for all your help!

Regards.
