### ISSUE TITLE
Spray 1.2.0 and phantom 1.9.8 have conflicts using shapeless

### ISSUE THREAD

**Issue by prsekar** [websudos/phantom#286]
We are trying to use phantom 1.9.8 in one of our projects which already uses spray routing (1.2.0). Our observation is the code which uses phantom fails with

[error] bad symbolic reference. A signature in ImplicitMechanism.class refers to term shapeless
[error] in package which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling ImplicitMechanism.class.
[error] bad symbolic reference. A signature in ImplicitMechanism.class refers to term package
[error] in value shapeless which is not available.

We did follow one of your other threads and excluded the shapeless as below, but that did not help.
val phantomDSL = "com.websudos" %% "phantom-dsl" % "1.9.8" exclude ("com.chuusai", "shapeless_2.10")

Any idea how to get away from this ? Is is ok to expect phantom to work with lower version of shapeless ?

**Comment by alexflav23** [comment]
Hi @prsekar,

Phantom uses only minimal functionality from shapeless and all open source phantom modules should in theory work with an older version of shapeless. That aside, perhaps you are excluding the wrong dependency and you should make sure you have indeed eliminated the dual dependency.

Using `evicted` or even the `External Libraries` dropdown from InteliJ in `Project Structure` should clear that out. Let me know if any of this is useful.

Regards,
Flavian

**Comment by jtjeferreira** [comment]
as I commented in #285 we use "io.spray" %%  "spray-routing-shapeless2" % SprayVersion,

**Comment by prsekar** [comment]
thanks jtjeferreira

we tried that and it works.

**Comment by prsekar** [comment]
Just a thought,
Like @alexflav23m mentioned, if phantom is not using shapeless extensively, can we not have a package 1.9.8 or any new version which is compiled with shapeless < 2.0.

In our case we had to upgrade spray to 1.3.x which might cause some regression.

**Comment by alexflav23** [comment]
Hi @prsekar,

Shapeless versions are incompatible between them. Phantom runs on a shared query engine for building and reflection functionality and while the OSS phantom uses little shapeless, it's bigger enterprise brother has enough shapeless for Miles Sabin to adopt it, and `phantom-enterprise` also depends on `phantom`.

This causes a fairly large logistical nightmare for the sole gain of using Spray, which may not reflect a large part of our audience. 

Regards,
Flavian
