### ISSUE TITLE
phantom 2.0.0

### ISSUE THREAD

**Issue by prsekar** [websudos/phantom#288]
Do we have RC version of phantom 2.0.0 that i can download from any bintray ???

**Comment by alexflav23** [comment]
Hi @prsekar,

2.0.0 isn't out yet. What specifically are you looking for? Which feature?

Regards.

**Comment by prsekar** [comment]
We are looking for user defined data types. Looks like the support is only from 2.0.0.

**Comment by alexflav23** [comment]
Hi @prsekar ,

UDTs have yet to reach stability. However, in all honesty, implementing flexible structures with JSON columns and blobs is equally trivial. Phantom already adds support for that and while I am very well aware I'm not exactly answering your question about UDT support, you can easily use JSON until UDTs are available.

It has proven to be somewhat painful to make UDTs work as fluently as we wanted in the Scala DSL and we are still exploring options to do things properly.

Regards,
Flavian

**Comment by D-Roch** [comment]
Nice, do you have an example ? I was also waiting for UDT support

**Comment by alexflav23** [comment]
Hi @D-Roch,

An example of using custom types is [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/db/specialized/JsonColumnTest.scala). The idea is simple, you just tell the column how to serialize/de-serialize and it can store things as blobs for you.

Regards,
Flavian

**Comment by manavgupta08** [comment]
Hi Flavian
We also need Optional Collection Column types. Is it already possible to define those ?

Thanks
Manav

**Comment by alexflav23** [comment]
Hi @manavgupta08,

It's possible sure, but instead when the are no elements we just return an empty collection, why do you need the extra wrapper type?

Regards.

**Comment by joosterman** [comment]
Hi @alexflav23 ,
What happens when I have stored a non-empty collection in column X and do an update and I don't want to update X? Specifically, what should happen with the existing value in the DB when
1) I set X to List.empty and do the update
2) I set X to null and do the update

This I guess then also holds for the insert case: What happens when I insert and empty collection? Does the row then have the column or is it not even created?
Kind regards,
Jasper

**Comment by alexflav23** [comment]
Hi @joosterman,

Not sure how this is related to 2.0.0 or why this comment is here. Also, this is not paid support so please try those things yourself before asking, I don't have the time for such requests unfortunately.

Regards,
Flavian

**Comment by joosterman** [comment]
@alexflav23 
This was the only issue I could find that already mentioned optional collections, so I though it would be better to tack onto this one then to start a new issue.
In this case you are right: I'll write some test to understand the currently implemented behaviour first.
