### ISSUE TITLE
Logged Batch statement execution using phantom 1.9.8

### ISSUE THREAD

**Issue by ngorijala** [websudos/phantom#289]
http://pythonhackers.com/p/websudos/phantom#logged-batch-statements

Is the write up mentioned in the above link valid for phantom 1.9.8.?? if not, can you please point to some documentation/examples for writing logged batch statements using phantom 1.9.8.??

**Comment by alexflav23** [comment]
Hi @ngorijala,

Check the Wiki page [here](https://github.com/websudos/phantom/wiki/Batch-statements).

Regards,
Flavian
