### ISSUE TITLE
getting some error while data modeling

### ISSUE THREAD

**Issue by dgrene** [websudos/phantom#294]
[RuntimeException: java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaMirrors$JavaMirror;]

this my table : 
CREATE TABLE Users(id timeuuid PRIMARYKEY, email text,name text,registrationDate text);

This my connector :

package common
import com.datastax.driver.core.Session
import com.websudos.phantom.connectors.{ ContactPoints, KeySpace, SimpleConnector }

trait Keyspace {
  implicit val space: KeySpace = new KeySpace("test_user")
}
object Defaults extends Keyspace {
  val hosts = Seq("docker.local", "127.0.0.1:9042")
  val Connector = ContactPoints(hosts).keySpace(space.name)
}
trait Connector extends Defaults.Connector.Connector with Keyspace

My modeling : 
case class User(
  id: UUID,
  email: String,
  name: String,
  registrationDate: String)

class Users extends CassandraTable[Users, User] {
  object id extends UUIDColumn(this) with PartitionKey[UUID]
  object email extends StringColumn(this)
  object name extends StringColumn(this)
  object registrationdate extends StringColumn(this)
  def fromRow(row: Row): User = {
    User(
      id(row),
      email(row),
      name(row),
      registrationdate(row))
  }
}
object Users extends Users with Connector {
  def store(user: User): ScalaFuture[ResultSet] = {
    println(user.id)
    insert.value(_.id, user.id).value(_.email, user.email)
      .value(_.name, user.name)
      .value(_.registrationdate, user.registrationDate)
      .consistencyLevel_=(ConsistencyLevel.ALL)
      .future()
  }
  def getById(id: UUID): ScalaFuture[Option[User]] = {
    select.where(_.id eqs id).one()
  }
}

**Comment by alexflav23** [comment]
Hi @dgrene,

I have never seen that before and everything looks ok at first glance. I will attempt to run your code later today and see what is wrong. Perhaps having the full stack trace would also be a lot more helpful, at the very least I can tell you if this is indeed phantom related.

Regards.
