### ISSUE TITLE
select.where 1.10.1 not working

### ISSUE THREAD

**Issue by mmoulou** [websudos/phantom#296]
Hello,

I'm planing to upgrade to phantom 1.10.1, but I'm facing some problems: 

I want to use "select.where", my class inherit "CassandraTable", or "select" method on SelectTable class return RootSelectBlock instead of SelectQuery, so, my select.where is not working anymore.

"value where is not a member of com.websudos.phantom.builder.query.RootSelectBlock"

How can i fix this?

tks

**Comment by alexflav23** [comment]
Hi @mmatloka,

`import com.websudos.phantom.dsl_` is missing.

**Comment by mmatloka** [comment]
@alexflav23 this was not me this time ;)

**Comment by alexflav23** [comment]
Hi @mmatloka, my apologies, Git autocompletion picked you and I didn't even realise :)

**Comment by raam86** [comment]
I am facing the same issue with 1.12.2 and included the import

**Comment by raam86** [comment]
```
livecf.select.count().where(_.id eqs id)
```
works while 
```
livecf.select.where(_.id eqs id)
```
Doesn't work. what gives?

**Comment by macalinao** [comment]
same

**Comment by alexflav23** [comment]
Hj @macalinao The recent version of phantom is 2.1.3, I'm not entirely sure what could be causing this, but 1.10.1 is not supported anymore as it's rather old. I would advice that you upgrade to one of the more recent versions.
