### ISSUE TITLE
Unresolved util-testing Dependency

### ISSUE THREAD

**Issue by bennythomps** [websudos/phantom#300]
I'm trying to pull the latest phantom library (1.10.1) and I'm getting unresolved dependencies for util-testing. I have added all the required resolvers and end up with unresolved errors.

Here are my two phantom dependency lines:

```
  "com.websudos" %% "phantom-testkit" % "1.10.1" % "test",
  "com.websudos" %% "phantom-dsl" % "1.10.1"
```

Here are my resolvers

```
resolvers ++= Seq(
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  "Websudos releases"                at "http://maven.websudos.co.uk/ext-release-local",
  "jcenter"                          at "http://jcenter.bintray.com"
)
```

**Comment by alexflav23** [comment]
Hi @bennythomps ,

You have an outdated resolvers list, I'm assuming you are upgrading perhaps. Look [here](https://github.com/websudos/phantom/wiki/Integrating-phantom-in-your-project), our Maven repo is now on Bintray. 

Remove "Websudos releases" or replace it's value with our Bintray repo and everything should be fine.

Regards.

**Comment by bennythomps** [comment]
:+1: thanks!
