### ISSUE TITLE
Multiple orderBy clauses

### ISSUE THREAD

**Issue by nkijak** [websudos/phantom#309]
Previously you could specify any clauses in the `orderBy` section of a query. Now it only takes one condition and seemingly locks the query to that one column because the `SelectQuery` type becomes `Ordered` and you can only `orderBy` when `Unordered`.

**Comment by alexflav23** [comment]
Hi @nkijak,

This is indeed a problem that we are addressing as we speak, a fix should be avaialable as early as today. The `orderBy` method was designed as a varargs method, meaning the right way to use it was:

`Table.select.where(_.a eqs b).orderBy(_.a asc, _.b desc, _.c asc)`. Off the top of my head it's possible this syntax doesn't actually work and you need to provide the full lambda during ordering, underscore notation may fail.

`Table.select.where(_.a eqs b).orderBy(t => { t.a asc, t.b desc, t.c asc })`. We will update you as soon as a fix has become available. Many thanks for the bug report.

Regards.

**Comment by alexflav23** [comment]
Hi @nkijak,

This has now been fixed as of phantom `1.13.0`. You can now use multiple `orderBy` clauses in the same statement just as I've described above.

Regards.

**Comment by nkijak** [comment]
@alexflav23 Thanks. Will check it out.
