### ISSUE TITLE
Can't resolve come.websudos - seems like incompatible versions

### ISSUE THREAD

**Issue by rashtapu** [websudos/phantom#311]
I'm getting errors resolving websudos in following imports:
import com.websudos.phantom.CassandraTable
import com.websudos.phantom.dsl._

Here's the build.sbt

version := "1.0"

scalaVersion := "2.11.7"
val phantomVersion = "1.12.2"

resolvers ++= Seq(
  "Typesafe repository snapshots" at "http://repo.typesafe.com/typesafe/snapshots/",
  "Typesafe repository releases" at "http://repo.typesafe.com/typesafe/releases/",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  "Websudos releases"                at "http://maven.websudos.co.uk/ext-release-local",
  "twitter-repo"                     at "http://maven.twttr.com",
  "websudos-repo"                    at "http://maven.websudos.co.uk/ext-release-local",
  Resolver.bintrayRepo("websudos", "oss-releases")
)

libraryDependencies ++= Seq(
  "com.datastax.cassandra" % "cassandra-driver-core" % "2.1.2",
  "com.websudos"  %% "phantom-dsl"                   % phantomVersion,
  "com.websudos"  %% "phantom-example"               % phantomVersion,
  //"com.websudos"  %% "phantom-scalatra"              % phantomVersion,
  //"com.websudos"  %% "phantom-spark"                 % phantomVersion,
  "com.websudos"  %% "phantom-thrift"                % phantomVersion,
  "com.websudos"  %% "phantom-testkit"               % phantomVersion,
  "com.websudos"  %% "phantom-udt"                   % phantomVersion,
  "com.websudos"  %% "phantom-zookeeper"             % phantomVersion
)

Any reason why this is not working?

**Comment by alexflav23** [comment]
Hi,

I think you have a broken resolver that we have long deprecated. Also you have an explicit dependency on the Java driver which is pointless and potentially dangerous. Let phantom set the driver version it needs. You also have a lot of dependencies you don't need.

The `build.sbt` file.

```
version := "1.0"

scalaVersion := "2.11.7"
val phantomVersion = "1.12.2"


resolvers ++= Seq(
  "Typesafe repository snapshots" at "http://repo.typesafe.com/typesafe/snapshots/",
  "Typesafe repository releases" at "http://repo.typesafe.com/typesafe/releases/",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  "twitter-repo"                     at "http://maven.twttr.com",
  Resolver.bintrayRepo("websudos", "oss-releases")
)

libraryDependencies ++= Seq(
  "com.websudos"  %% "phantom-dsl"                   % phantomVersion
)
```

**Comment by rashtapu** [comment]
Thank you for your response, it worked.
