### ISSUE TITLE
websudos maven repo not available

### ISSUE THREAD

**Issue by bbirand** [websudos/phantom#312]
It seems that the websudos Maven repo is not accessible. I'm new to the Scala world, is it common for each project to have its own repository? I have no doubt it will be back up in no time, but what if I had to compile `phantom` during in a deployment script? Is it not possible to host all files on a main repo?

Thanks!

```
[error] Server access Error: Operation timed out url=http://maven.websudos.co.uk/ext-release-local/co
m/websudos/diesel-engine_2.11/0.2.2/diesel-engine_2.11-0.2.2.pom
```

**Comment by alexflav23** [comment]
Hi @bbirand,

That repo has been deprecated for over half a year, please remove it from the build script and everything should return to normal. Read the main readme and add the correct Bintray resolvers.

Regards.

**Comment by bbirand** [comment]
I see. I was going by the home page:
http://websudos.github.io/phantom/

**Comment by alexflav23** [comment]
Thank you for pointing that out, we will update the main readme as well.
