### ISSUE TITLE
Cassandra 2.2.1

### ISSUE THREAD

**Issue by evgenyigumnov** [websudos/phantom#313]
Hi do u support this version?

I try to store object but after store it is say ok but cassandra table is empty

I down grade from 2.2.1 to 2.1.7 and store starting work

why?

**Comment by alexflav23** [comment]
Hi @evgenyigumnov,

If there was a failure you would get an error. I think in the latest version `1.12.2` we support Cassandra 2.2.0 and upwards, I'm not sure if 2.2.1 is somehow different and requires driver level changes but it doesn't sound like it should be a problem.

Do you see any errors?

**Comment by evgenyigumnov** [comment]
Unfortunately no errors. Just dont store row in database. With silence.

**Comment by alexflav23** [comment]
Hi @evgenyigumnov,

Cassandra 2.2.1 is now on the roadmap and support should be available in the coming weeks. So far we never officially supported it and it's somewhat strange there's such a big obvious problem in spite of having a successful connection. I think there may well be other factors at play, but we will see when support is enabled.

**Comment by timcharper** [comment]
This is good to know; would be nice to have been advised of this earlier :) I got all the way down to realize that my consistency level queries weren't working.

Nice work on the library.

**Comment by alexflav23** [comment]
Hi @timcharper ,

I think consistency level queries will be restored to good working order. There was a small version comparison issue inside phantom that was fixed and will be available in the next incremental release.

Regards.
