### ISSUE TITLE
No error without specified partition key

### ISSUE THREAD

**Issue by tyth** [websudos/phantom#314]
Here https://github.com/websudos/phantom/wiki/Indexes it's written that:

>You must define at least one partition key for a table. Phantom will gently remind you of this with a fatal error.

But I succesfully ran application and retrieved results, while no key was specified.
Either the documentation is wrong or there is some bug.

PhantomVersion = "1.12.2"

**Comment by brianwawok** [comment]
You used phantom to query an existing table, or to create a new table? 

If so, what did your table look like?  Cassandra won't let you make this table..

**Comment by alexflav23** [comment]
@tyth I don't think everything is right, as @brianwawok points out it wouldn't be possible to create such a table in the first place so I don't see how this happens. Could you please post some code here?

**Comment by tyth** [comment]
I queried existing table. I didn't understand that this note was about schema creation only.

**Comment by alexflav23** [comment]
Hi @tyth,

Apologies, we will update the documentation to be more specific. The check is a schema generation check indeed, so after the table is created no checks are ever run outside of the where clauses which will require that you use a partition or primary inside them(or a secondary index at the very least).
