### ISSUE TITLE
Support for TTL in Update query

### ISSUE THREAD

**Issue by tyth** [websudos/phantom#315]
In cassandra cql documentation it's said that you can specify ttl in update query:
https://cassandra.apache.org/doc/cql/CQL.html#update

And there is no support for it in DSL (https://github.com/websudos/phantom/wiki/Querying)

Are you planning to add such support? Is there any graceful workaround for now?

**Comment by alexflav23** [comment]
Hi @tyth ,

This looks like an oversight, this will be resolved very quickly and should be out in the next incremental release. I will try and release today itself to fix this and keep you posted.

Regards.

**Comment by alexflav23** [comment]
Hi @tyth ,

This should now be available in Phantom `1.13.0`. 

Regards.
