### ISSUE TITLE
Querying optional columns ?

### ISSUE THREAD

**Issue by Baccata** [websudos/phantom#316]
Does the current state of Phantom allows querying on optional columns ?

**Comment by alexflav23** [comment]
Hi @Baccata,

No, and for a very good reason. Indexes in Cassandra are not nullable or you would break the contract Cassandra uses to nest data and form keys. As a result it doesn't really make sense to allow such queries at DSL level.

In principle you should never query over something that can be `None`. Instead, create a new table where the option you want to query by is no longer an option. Do things the NoSQL way with duplication and you should be on track.

Hope this help, let me know if you need more help!

Regards,
Flavian
