### ISSUE TITLE
Diesel engine missing from maven central

### ISSUE THREAD

**Issue by brianwawok** [websudos/phantom#317]
It seems your maven central publishing got out of wack again.

You can go here and find phantom-dsl_2.11-1.12.2

https://repo1.maven.org/maven2/com/websudos/phantom-dsl_2.11/1.12.2/phantom-dsl_2.11-1.12.2.pom

One dependency that is in the pom is "diesel-engine_2.11-0.2.2"

But there is no such thing as diesel-engine in maven central

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.websudos%22%20AND%20a%3A%22diesel-engine%22

**Comment by alexflav23** [comment]
Hi @brianwawok,

That's because the engine lives on Bintray.`https://bintray.com/websudos/oss-releases`.

Regards.

**Comment by jtjeferreira** [comment]
Isn't the source code for this diesel engine available in github/bitbucket?

**Comment by alexflav23** [comment]
Hi @jtjeferreira,

None of our code is open source, it's just free to use. You can not re-distribute it,  offer paid support for it or anything like that or you are in breach of license. The code for diesel is not public as of yet and only a very small part of it is available for free wide spread consumption.

**Comment by jtjeferreira** [comment]
I was just asking because phantom source code is available online for browsing while for diesel I couldn't find anything.

However in https://bintray.com/websudos/oss-releases/phantom-dsl/view it is stated that the license is Apache which makes it OSS right?

Regards

**Comment by alexflav23** [comment]
Hi @jtjeferreira,

No it doesn't, the only license under which phantom is available is our proprietary license. We have no plans of releasing any of our trademark products as OSS, they remain however free to use.

Regards.

**Comment by jtjeferreira** [comment]
Thanks for the clarification

**Comment by brianwawok** [comment]
@alexflav23 the problem with this approach (Put an artifact in Maven Central put half of it's dependencies in Bintray) is generally super screwy and does not work very well.  You are really much better off going ALL bintray (and moving maven central) or ALL maven central (and removing Bintray). The maven central partial release is adding no value as you still need to go off to bintray to use it...

**Comment by raam86** [comment]
@alexflav23  at the very least you should point this out in the README. You didn't even update it here https://github.com/websudos/phantom-activator-template
