### ISSUE TITLE
Use immutable ByteString or ByteVector for blob columns

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#318]
Right now, `ByteBuffers` are used for Blob column types.  Having done this with Phantom, though, there are issues: ByteBuffers are mutable and very dangerous to work with.

Ideally we want something which is 1) immutable, and 2) can hashCode correctly and be used as keys in HashMaps, yet still allows 3) random access.

Array[Byte] is mutable, slightly better than ByteBuffer, but does not hashCode.
Instead, let's look into these alternatives:

https://github.com/scodec/scodec-bits - has a ByteVector type
Akka's ByteString - https://github.com/akka/akka/blob/v2.3.5/akka-actor/src/main/scala/akka/util/ByteString.scala - just copy this file so that the core module doesn't need to link in Akka

Related issue in my own project:  https://github.com/velvia/FiloDB/issues/12

**Comment by alexflav23** [comment]
Hi @velvia,

I certainly understand the concern. We can add adjacent functionality to existing blob columns, release them, and see how they behave in practice.

Regards.

**Comment by alexflav23** [comment]
@velvia Fixed in `0.12.3`, release just went out to Bintray yesterday. You can use `ByteStringColumn` which will return a `ByteString`. Hope this helps, please let me know if you can make any improvements to the current implementation of parsing from and to a `ByteString`.

**Comment by velvia** [comment]
Thanks guys.  Bummer, I decided to use ByteVector in my project.  ByteString is good too though, thanks.
