### ISSUE TITLE
Question - shutdown proces

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#321]
Hi,
I would like to ask, what is the proper ways to close all sessions and connections phantom is using. I have a small batch app, which after using phantom never ends its execution. So far I have found that after running:
```
 Manager.shutdown()
 connector.session.getCluster.close()
```
application is able to end its execution. Is this the proper way to close this, or are there any other API methods for that? :)

**Comment by alexflav23** [comment]
Hi @mmatloka,

This is the way to close down yes, the phantom manager shuts down whatever phantom uses internally and the session should close whatever the Datastax bit handles.

Regards.
