### ISSUE TITLE
Bintray repo always needed?

### ISSUE THREAD

**Issue by futurechimp** [websudos/phantom#324]
Hi there, 

When using Phantom 1.12.2 from `search.maven.org`, I kept getting a 404 on the `util-testing` depdendency:

```
com.websudos#util-testing_2.11;0.9.6: not found
```

This was a little confusing, especially late at night. But I slept on it, then in the morning added this to my resolvers:

```scala
resolvers += "Websudos Bintray Repo" at "https://dl.bintray.com/websudos/oss-releases/",
```

That worked. 

Do you want a pull request against your docs to try and make this a bit more clear? I read the docs to mean that the stable artefacts on maven.org wouldn't require any additional resolvers, and that I only needed to add the Bintray repo to my resolvers if I was using intermediate releases. 

Or maybe there's just a rogue dependency in there somewhere? :)

**Comment by alexflav23** [comment]
Hi @futurechimp,

Thank you for your proposal, but this is already specified in the default guide:

`https://github.com/websudos/phantom/wiki/Integrating-phantom-in-your-project`.

Regards.
