### ISSUE TITLE
Proper support for CQL TOKEN(partkey1, partkey2)

### ISSUE THREAD

**Issue by velvia** [websudos/phantom#330]
Hi guys,

I need support for CQL queries of the type

SELECT col1, col2 FROM table WHERE TOKEN(partkey1, partkey2) > tokenNum;

ie support of token scans when a table defines multiple partition keys.  Currently looking at the code this does not seem to be supported.

1. Is there any workaround, like I can manually pass the CQL query string to Phantom?
2. I'm willing to work on a PR if you guys show some guidance as to the query syntax to support this.  The current examples of doing `where(partkey1 gttoken val)` would not work, and would need two modifications:
    a. Something to specify multiple partition keys, like `where((partkey1, partkey2) gttoken val`
    b. Also, specifying a value for partition keys doesn't make sense esp if the goal is to divide the token range up matching it to what Cassandra gives you.  Instead it would be better to specify the token value itself.

**Comment by alexflav23** [comment]
Hi @velvia ,

With apologies for a long overdue reply, this wouldn't be impossible. We already have something called `Operators` which operate in flight, meaning you simply "drop" them in the middle of the `where` clause.

This could be done with a `Token` object that has a varags apply method accepting partition columns that creates another type, say `TokenOp`, which has comparisons defined for it and the final result between a tokenOp and a comparison is a `WhereClause.Condition`.

It's a bit convoluted perhaps if you are not familiar with the codebase, but it's very easy in fact. We will try to add shortly and notify you when it's available.

Regards.

**Comment by velvia** [comment]
Awesome thanks!

**Comment by alexflav23** [comment]
Hi @velvia ,

Most of this is already underway, but it would be useful to understand what the expect values are on the righthand side of the comparison.

Assuming we have this:

```scala
Table.select.where(t => { token(t.id, t.id2) > someValue })
```
What should some value be in that case? What phantom does when you provide a value inside the `gtToken` clause is to apply a token call to both sides, so you would end up with something like: 

```scala
SELECT * FROM phantom.ArticlesByAuthor WHERE TOKEN (author_id) > TOKEN(83cabcaa-4cc9-4da8-b373-5f8baf07664a);
```

I've copy pasted that from a test output, so that's definitely the current behaviour. Maybe the word `value` is confusing or the naming not obvious, but otherwise please let me know if all the behaviour is correct with respect to expectations.

**Comment by velvia** [comment]
I think when one works with tokens, they are likely manipulating token ranges as returned by the Cassandra topology….. so basically if we can pass in the Token class from the CQL java driver that would be perfect.

Thanks!

**Comment by alexflav23** [comment]
Hi @velvia,

Version `1.17.3` now includes a token operator that supports token queries of any arity. There are some strange compiler bugs strill preventing full type-safety, which is to do with a limitation in shapeless `Generic` or the compiler itself.

You can write queries like the following, or the other way around with values first.

```
Table.select.where(table => { token(table.col1, table.col2) > token("a", "b")})

``` 
Regards.

**Comment by velvia** [comment]
Is it possible to do queries of the form token(table.col1, table.col2) > myToken where myToken comes directly from the CQL driver Token class?   That’s what I really need.
