### ISSUE TITLE
Cassandra 3.0.0 support

### ISSUE THREAD

**Issue by pjan** [websudos/phantom#336]
With Cassandra having released an RC2 for 3.0.0, the final is getting close. What are the plans for supporting this? Any assessment done on the impact, as well as expectations for when it would land?

Currently assessing to use phantom for our production, hence the question.

**Comment by alexflav23** [comment]
Hi @pjan,

Cassandra 3.0.0 will definitely be supported but it's not on the roadmap as of yet until the Java Driver also hits a good milestone release. As adopting the very bleeding edge of Cassandra is highly unlikely to be high priority for any large consumer, it will take perhaps weeks to see this through.

Hope this answers your question!

Regards.

**Comment by phact** [comment]
https://github.com/datastax/java-driver/tree/3.0.0

**Comment by alexflav23** [comment]
Hi @phact,

We are already running a 3.0.0 milestone release, we will bump to final very shortly.

Regards.

**Comment by Konstantin-Skachkov** [comment]
What is the ETA?

**Comment by alexflav23** [comment]
HI @Konstantin-Skachkov, 

This is already out, both `1.22.0` on Maven Central and `1.24.0` on Bintray are compatible with Cassandra 3.0.

Regards.
