### ISSUE TITLE
Any thoughts of supporting the JSON CQL clause?

### ISSUE THREAD

**Issue by richbolen** [websudos/phantom#337]
I would like to use phantom with the JSON CQL clause added in V2.2 of Cassandra.  

i.e.:   INSERT INTO some_keyspace.some_table JSON '{some json string}'

Is this possible?  If not do you know how I could extend phantom to add that capability?

**Comment by alexflav23** [comment]
Hi @richbolen ,

We don't yet support the native Cassandra functionality for JSON columns, but phantom had support for `JsonColumn` for a very long time, which is essentially the same thing but you have to provide serialization/de-serialization.

Have a look [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/tables/JsonTable.scala).

That being said, we do plan to support all new Cassandra features in upcoming releases, so in a few weeks we will support the native functionality as well.

**Comment by richbolen** [comment]
Thanks for the prompt reply Alex!  

We have dozens of model classes, some with hundreds of fields, so I'd like to avoid creating a CassandraTable per model class.  Supporting the JSON clause is one way to get around it.

**Comment by alexflav23** [comment]
@richbolen This is now available in phantom 1.14.2. We haven't added support for `UPDATE` clauses and the `fromJson` and `toJson` CQL clauses yet but it will come in a future release. Inserts are however available and working.

**Comment by richbolen** [comment]
Thanks!  That was a quick turn-around.  I wasn't expecting it to be so quick so I went ahead and modified your code to add both insert and select JSON support.  I was going to submit it back to you.  

Funny, I went back and forth between creating a new query type and extending the existing query types.  I ended up extending the existing types but it looks adding a new query type is cleaner.  A few more notes about my code.  We use a newer version of liftweb (json4s) so my code uses json4s instead of liftweb.  We use case sensitive column names quite a bit so there is a lot of messy code making sure keyspace, table, and column names all support case sensitivity for the json strings.  You could probably clean that up quite a bit.

Do you want me to submit my code back to you?  Feel free to borrow as much or as little as you like.  I didn't know the backstory for your driver development so I was guessing a lot when I modified it.  

BTW - for now we will use my code but our hope is to migrate to your production version as soon as it gives us everything we need.  

Cheers,
Rich
