### ISSUE TITLE
how to use maxTimeuuid function on phantom

### ISSUE THREAD

**Issue by mmoulou** [websudos/phantom#339]
Hello,

I didn't find a way to use maxTimeuuid function with phantom Dsl on timeuuid column
I'm wondering whether this functionality exists or not

tks

**Comment by alexflav23** [comment]
Hi @mmoulou ,

I think we are missing some of the operator functionality but that shouldn't be too hard to add. With apologies for the late reply on our behalf, we will add this to the roadmap and work on it the coming week, it should surface sometimes towards the end of it.

Regards.

**Comment by alexflav23** [comment]
Hi @mmoulou ,

This has now been addressed as of phantom `1.13.0`. Examples [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/serializers/SelectQuerySerialisationTest.scala#L31).

Regards.

**Comment by mmoulou** [comment]
Very nice, thanks for your prompt feedback!

**Comment by mmoulou** [comment]
i've the same issue with Token function, i don't know how tu use token function on phantom
