### ISSUE TITLE
Cassandra 2.2.x - aggregates support, min, max etc

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#349]
Since Cassandra 2.2.x is already stable, do Phantom supports `min`, `max` etc functions ? :)
http://christopher-batey.blogspot.com/2015/05/cassandra-aggregates-min-max-avg-group.html

**Comment by alexflav23** [comment]
Hi @mmatloka ,

We are in the process of releasing extensive support for all the fun features upcoming in Cassandra, including aggregates combined with extensive support for Spark. They will however only be available in the licensed version of phantom which we plan to release in Q1 2016.

It also bundles things like:
- automated schema resolutions
- automated SQL DB to Cassandra transitions 

It will all be available for a very low license fee and we plan to use the income generated to fund development of our other open source work. 

Regards.

**Comment by alexflav23** [comment]
Hi @mmatloka,

I'm going to close this as it's not really a relevant issue for the OSS project. We will keep everyone up-to-date on the developments of the enterprise version.

Regards.
