### ISSUE TITLE
Reactive Cassandra (with Phantom DSL)

### ISSUE THREAD

**Issue by juanjovazquez** [websudos/phantom#350]
@alexflav23 We've noticed that you've [copied](https://github.com/websudos/phantom/pull/348/files) the [reactive-cassandra-phantom](https://github.com/Tecsisa/reactive-cassandra-phantom) code in your develop branch . This is perfectly ok as we licensed the software under the Apache 2.0 terms. This means that you liked the code so we're really happy about it!.

We really appreciate your effort in phantom and we're using it in our projects for several months. On the other hand, we'd have liked to speak about your interest in this reactive streams development before so that we could have maybe raised a PR and avoid the code duplication.

Our next steps regarding the project are to take advantage of prepared statements as we've checked that the benefits of using them in large workloads really worth it. This is especially useful in streaming scenarios. It'd be great if we could collaborate to make this happen in the phantom code base.

Regards

**Comment by alexflav23** [comment]
Hi @juanjovazquez ,

Many thanks for reaching out, indeed we have, we took the implementation and cleaned up some of the duplication and added a publisher on top of the existing subscriber implementation. The code is somewhat different, but we felt more widespread adoption of reactive streams might be beneficial and our friends at Typesafe also thought it might be a good idea to add native support as well.

In the future, please don't hesitate to communicate any plans whatsoever or to request new features. Prepared statements area already available as of phantom 1.15.0, they are in experimental status at this point in time so please feel free to test them and report any bugs you might find.

Regards,
Flavian
