### ISSUE TITLE
RS: BatchSubscriber should allow a stream of Throwables to be persisted

### ISSUE THREAD

**Issue by rkuhn** [websudos/phantom#352]
Currently stream failures are sent to the BatchActor without wrapping them. If a data element (of type T) happens to be derived from Throwable then this will be mistaken as a stream failure instead of being written to Cassandra.

**Comment by alexflav23** [comment]
Hi Roland,

I hope you made it home ok and thanks for taking the time to provide feedback. Dully noted, we will add a wrapper class to avoid the potential culprit. I will update you as soon as that's patched, please feel free to provide any more feedback. At this point in time, extensive tests are also missing for the publisher so that's already on our TODO list.

Regards.

**Comment by rkuhn** [comment]
Thanks, Flavian!

**Comment by alexflav23** [comment]
We are now using a `WrappedRequest` to send elements regardless of their root type so there won't be any danger of running into the described issue. The workaround is [here](https://github.com/websudos/phantom/blob/feature/streams_improvement/phantom-reactivestreams/src/main/scala/com/websudos/phantom/reactivestreams/ReactiveCassandra.scala#L114) and the overheard/boilerplate should be minimal.

**Comment by alexflav23** [comment]
@rkuhn I also noticed on your patch branch on your fork of phantom(no PR yet from there as one of your comments suggested) that using `null` directly is preferred. I can certainly revert back to that inside the actor for retrieving the `ActorRef`.

**Comment by rkuhn** [comment]
Wouldn’t it be more efficient to just wrap the Throwables and let the elements be sent without wrapping?

**Comment by alexflav23** [comment]
A great point as always, will update.

**Comment by alexflav23** [comment]
@rkuhn This has now been fixed and ready to be closed, which just leaves us with the `flushInterval` problem. Being not super familiar with the reactive streams rules, I'm not sure how best to address this issue, although I do see how forcing execution could lead to more problems.

**Comment by rkuhn** [comment]
Yes, looking good on the feature branch.
