### ISSUE TITLE
RS: BatchSubscriber should check for overflow

### ISSUE THREAD

**Issue by rkuhn** [websudos/phantom#353]
Requesting `batchSize * concurrentRequests` elements may overflow, in which case `Long.MaxValue` should be used to signal “infinite” demand (well, the reasonable thing to do would be to have a long educational chat with the developer in question, but a library cannot do that, so we should at least be RS compliant).

**Comment by alexflav23** [comment]
Hi @rkuhn,

We could enforce a `Math.multiplyExact` for Java 8 although this would imply a strong limitation on the entire library to depend on Java 8 for a small clause, maybe in a few years when version 7 is forgotten if ever.

For now I just copied the implementation of `Math.multiplyExact` and we can actively enforce the limitation at library level via:

```scala
def multiplyExact(x: Long, y: Long): Long = {
    val r: Long = x * y
    val ax: Long = Math.abs(x)
    val ay: Long = Math.abs(y)
    if (((ax | ay) >> 31) != 0) {
      if (((y != 0) && (r / y != x)) || (x == Long.MinValue && y == -1)) {
        throw new ArithmeticException("long overflow")
      }
    }
    r
  }

val requestSize = Try {
        multiplyExact(batchSize, concurrentRequests)
      } getOrElse Long.MaxValue

      s.request(requestSize)
```



Regards,
Flavian

**Comment by rkuhn** [comment]
Looks good, but when inlining the code anyway I’d refrain from using exceptions for flow control—creating that ArithmeticException takes an insane amount of cycles. What about renaming to multiplyCapped or similar and just returning `Long.MaxValue` upon overflow?

**Comment by alexflav23** [comment]
Excellent suggestion, will update.

**Comment by alexflav23** [comment]
I think this can be closed now, the final result is [here](https://github.com/websudos/phantom/blob/feature/streams_improvement/phantom-reactivestreams/src/main/scala/com/websudos/phantom/reactivestreams/ReactiveCassandra.scala#L81).

**Comment by rkuhn** [comment]
Yes, thanks!
