### ISSUE TITLE
Prepared statement - Codec not found for requested operation: [decimal <-> scala.math.BigDecimal]

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#359]
Like in the title :)

**Comment by alexflav23** [comment]
@mmatloka Would've probably been a good idea on our end to pre-sample this for all primitive types, but for reasons unknown it has yet to be done.

**Comment by alexflav23** [comment]
Hi @mmatloka,

This will be available in 1.17.0.

Regards.

**Comment by mmatloka** [comment]
Thx

**Comment by mmatloka** [comment]
https://github.com/websudos/phantom/commit/372e73f1271f88fecef9a91d16dc310322751a06#commitcomment-14633460 to be reopened :)
