### ISSUE TITLE
Warning re-preparing prepared statement although created only once

### ISSUE THREAD

**Issue by mmatloka** [websudos/phantom#360]
Hello again :)

I was trying to leverage prepared statements when I got:
```2015-11-24 13:09:08,925 [cluster1-nio-worker-1] WARN  com.datastax.driver.core.Cluster:2077 - Re-preparing already prepared query INSERT INTO .... Please note that preparing the same query more than once is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. ``` although my statement was theoretically created only once. I have looked into phantom tests and made a quick experiment.

I have modified the `PreparedInsertQueryTest` to include two inserts using the same statement and it results in the datastax driver warning:

```

class PreparedInsertQueryTest extends PhantomCassandraTestSuite {

  override def beforeAll(): Unit = {
    super.beforeAll()
    Recipes.insertSchema()
  }

  it should "serialize an insert query" in {

    val sample = gen[Recipe]

    val query = Recipes.insert
      .p_value(_.uid, ?)
      .p_value(_.url, ?)
      .p_value(_.servings, ?)
      .p_value(_.ingredients, ?)
      .p_value(_.description, ?)
      .p_value(_.lastcheckedat, ?)
      .p_value(_.props, ?)

    val exec = query.bind(
      sample.uid,
      sample.url,
      sample.servings,
      sample.ingredients,
      sample.description,
      sample.lastCheckedAt,
      sample.props
    ).future()

    val exec2 = query.bind(
      sample.uid,
      sample.url,
      sample.servings,
      sample.ingredients,
      sample.description,
      sample.lastCheckedAt,
      sample.props
    ).future()

    val chain = for {
      store <- exec
      test <- exec2
      get <- Recipes.select.where(_.url eqs sample.url).one()
    } yield get

    whenReady(chain) {
      res => {
        res shouldBe defined
        res.value shouldEqual sample
      }
    }
  }

}
```

```13:11:40.021 [cluster1-nio-worker-2] WARN  com.datastax.driver.core.Cluster - Re-preparing already prepared query INSERT INTO phantom.Recipes (uid, url, servings, ingredients, description, lastcheckedat, props) VALUES(?, ?, ?, ?, ?, ?, ?). Please note that preparing the same query more than once is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once.```

The `prepare` https://github.com/websudos/phantom/blob/093176a6145d62af43a0962a403c86a73ab04311/phantom-dsl/src/main/scala/com/websudos/phantom/builder/query/ExecutableQuery.scala#L94 method should be executed only once when creating prepared statement. This might require some additional API method like:

```    
      val query = Recipes.insert
      .p_value(_.uid, ?)
      .p_value(_.url, ?)
      .p_value(_.servings, ?)
      .p_value(_.ingredients, ?)
      .p_value(_.description, ?)
      .p_value(_.lastcheckedat, ?)
      .p_value(_.props, ?)
      .prepare()
```

**Comment by alexflav23** [comment]
Hi @mmatloka,

This is now fixed in the upcoming `1.17.0`, it should be ready to go today.

Regards,
Flavian
