### ISSUE TITLE
Inserting NULL values.

### ISSUE THREAD

**Issue by coreyauger** [websudos/phantom#377]
I am getting an issue where there are sometimes conditions in the system that are allowing for NULL values to be inserted.

Here is an example mapping 
```scala
object collaboration_id extends UUIDColumn(this) with PartitionKey[UUID] // with StaticColumn
    object content_id extends TimeUUIDColumn(this) with ClusteringOrder[UUID] with Descending

    object authors extends JsonSetColumn[GetCollaborationContent, Collaboration.Content, Auth.ProfileInfo](this) with Mapper {
      override def fromJson(obj: String): Auth.ProfileInfo = {
        mapper.readValue[Auth.ProfileInfo](obj)
      }
      override def toJson(obj: Auth.ProfileInfo): String = {
        mapper.writeValueAsString(obj)
      }
    }

    object seen_by extends JsonSetColumn[GetCollaborationContent, Collaboration.Content, Auth.ProfileInfo](this) with Mapper {
      override def fromJson(obj: String): Auth.ProfileInfo = {
        mapper.readValue[Auth.ProfileInfo](obj)
      }
      override def toJson(obj: Auth.ProfileInfo): String = {
        mapper.writeValueAsString(obj)
      }
    }

    object organization extends UUIDColumn(this)
    object content_path extends OptionalStringColumn(this)
    object content_sentiment extends OptionalStringColumn(this)
    object content_nlp extends OptionalStringColumn(this)
    object content extends OptionalStringColumn(this)
    object content_type extends StringColumn(this)
    object content_class extends StringColumn(this)
    object content_uri extends StringColumn(this)
    object content_cover extends OptionalStringColumn(this)
    object content_meta extends MapColumn[GetCollaborationContent, Collaboration.Content, String, String](this)
```

With a simple insert ...

```scala
def insertRecord(h: Collaboration.Content) = {
      val cUUID = UUID.fromString(h.collaborationId)
      val conUUID = UUID.fromString(h.id)
      val orgUUID = UUID.fromString(h.orgId)
      insert
          .value(_.collaboration_id, cUUID)
          .value(_.content_id, conUUID)
          .value(_.organization, orgUUID)
          .value(_.authors, h.authors)
          .value(_.seen_by, h.seen)
          .value(_.content_path, h.path)
          .value(_.content_sentiment, h.sentiment)
          .value(_.content_nlp, h.nlp)
          .value(_.content, h.content)
          .value(_.content_type, h.contentType)
          .value(_.content_class, h.contentClass.`class`)
          .value(_.content_uri, h.contentUri)
          .value(_.content_meta, h.meta)
          .future()
      }
```

I am seeing `organization` as null in some cases.  Not sure how this is possible since an exception should be thrown?

The only other update to this col happens with this call here.

```scala
def hasBeenSeenBy(collaborationId:UUID, contentId:UUID, read:Auth.ProfileInfo) = {
      GetCollaborationContent.update
        .where(_.collaboration_id eqs collaborationId)
        .and(_.content_id eqs contentId)
        .modify(_.seen_by add read)
        .future()
    }
```

I know I must be missing something... would appreciate any help you can give.  Thanks :)

**Comment by coreyauger** [comment]
After digging around it appears this has to be caused from my update.  Sorry for the trouble.

**Comment by thiagoandrade6** [comment]
@coreyauger  Actually, how did you solve this problem? I'm also facing this kind of null and I don't see phantom's complaining about that.

**Comment by coreyauger** [comment]
If I remember correctly there was something subtle going on with my update.. Do you have any updates that you call... I would check and re-check the logic to those.. as it had nothing to do with the insert from what I remember. Hope that helps.

**Comment by thiagoandrade6** [comment]
I have updates like this:

```
update
      .where(_.key1 eqs t.key1)
      .and(_.key2 eqs t.key2)
      .modify(_.mySet add valueToSet)
      .future()
```

What I'm trying to do is to add a new value to a set, and it works like a charm on tests and even on production, but some times, all the rest of the fields got null for a reason that I don't know.

=(

**Comment by coreyauger** [comment]
this was the same issue I had.. and I am searching my brain to try and remember what I did ... can you narrow it down to a specific case that causes the NULL?

**Comment by coreyauger** [comment]
Hey .. might be a little late on this one.. but I remember what it was now.  

My update was keying into a record that did not exist.. so the `partition keys` and `cluster keys` where there .. along with the value that I was adding to the set.. but of course the other values where NULL.  So the lesson here is that insert checks constraints.. where update/upsert does not.

Anyhow.. better late then never right ;)

**Comment by thiagoandrade6** [comment]
@coreyauger Great, thanks for your help. Actually we have not seem that anymore, the problem now is gone, however in case it is back, I will look closer to see if we are not updating something that does not exist, causing an upsert with null values.

**Comment by alexflav23** [comment]
Hi @evis, you can explicitly use `insert.value(bla).using(ignoreNulls)`.

**Comment by evis** [comment]
Thx for the tip @alexflav23, but I'm not sure if it will be helpful for me. I don't want to insert nulls/empty values at all, but due to some reasons (seems related to some node failures) on some reads I receive "Column my_column is null" exceptions.

**Comment by alexflav23** [comment]
Hi @evis That means something else, it means you have `null` values in places where you don't use Optional columns, so phantom expects them to be mandatory.

**Comment by thiagoandrade6** [comment]
@evis It's seems that you problem is different than the original issue I was talking related to updates. It's better to follow the @alexflav23 tip on changing the column to optional, so then you can analyze it further to understand what's happening.

**Comment by Funmbi24** [comment]
@evis were you able to fix this? If so. please share how. I seem to be experiencing the same

**Comment by evis** [comment]
No, I wasn't.
