### ISSUE TITLE
adding consistencyLevel_ to a select causes a double where clause

### ISSUE THREAD

**Issue by crispywalrus** [websudos/phantom#380]
select.where(...).consistencyLevel_=(...) ends up generating the cql "SELECT ... WHERE ... WHERE ...;"

**Comment by alexflav23** [comment]
@crispywalrus This is now fixed and will be available in `1.18.0`.

**Comment by crispywalrus** [comment]
That's quick! you got this before I'd even figured out where the problem was, thanks a lot.
