### ISSUE TITLE
Cannot use prepare statement - Cannot prove that VL1 =:= Reversed.

### ISSUE THREAD

**Issue by lahirug** [websudos/phantom#386]
First I am not sure this is my user error or not. I have a very simple code for preparestatement and I get following error in bind line.

TimeSeriesBySessionUuidAndKey.scala:110: Cannot prove that VL1 =:= Reversed.

This is my code: 
  def prepareInsert(timeSeries: TimeSeriesValue): Future[ResultSet] = {
    val query = insert
      .p_value(_.sessionId, ?)
      .p_value(_.key, ?)
      .p_value(_.time, ?)
      .p_value(_.value, ?)
      .prepare()

    query.bind(
      timeSeries.sessionId,
      timeSeries.key,
      timeSeries.time,
      timeSeries.value
    ).future()
  }

**Comment by lahirug** [comment]
This weired error comes when simply follow the phantom prepare statement sample. This is because of scala not picking the tuple for the bind statement. I think its a good idea to fix the sample with paranthesis for the tuple.

query.bind(
(timeSeries.sessionId,
  timeSeries.key,
  timeSeries.time,
  timeSeries.value
)).future()

**Comment by alexflav23** [comment]
HI @lahirug ,

Yes, this is an error on your end, but it's a simple one to fix. Basically, you need to make you provide bind arguments that exactly match the bind order, which is something you are already doing. 

Now, the type of one of your arguments `timeSeries.sessionId`, `timeSeries.key`, `timeSeries.time`, `timeSeries.value` is not matching the type phantom expects for that kind of column. A very simple way to check this to write a simple `insert.value(_.bla, bla)` query and try to compile that with your `timeSeries` object.

Hope this helps! That bind method is unfortunately a bit more complicated than we would like.

Regards,
