### ISSUE TITLE
Not able to configure LeveledCompactionStrategy subproperties

### ISSUE THREAD

**Issue by dbakarcic** [websudos/phantom#402]
Hi there, 
 I wanted to configure some specific subproperties for the `LeveledCompactionStrategy` (LCS) at table creation time, but looking at the docs or the source code I didn't find a way to do so. The only options I found are for the `SizeTieredCompactionStrategy` (STCS), and the implementation is the following:

```
sealed class SizeTieredCompactionStrategy(override val qb: CQLQuery) extends CompactionStrategy(qb) {
    def min_sstable_size(unit: StorageUnit): SizeTieredCompactionStrategy = {
      new SizeTieredCompactionStrategy(QueryBuilder.Create.min_sstable_size(qb, unit.toHuman()))
    }

    def sstable_size_in_mb(unit: StorageUnit): SizeTieredCompactionStrategy = {
      new SizeTieredCompactionStrategy(QueryBuilder.Create.sstable_size_in_mb(qb, unit.toHuman()))
    }

    def bucket_high(size: Double): SizeTieredCompactionStrategy = {
      new SizeTieredCompactionStrategy(QueryBuilder.Create.bucket_high(qb, size))
    }

    def bucket_low(size: Double): SizeTieredCompactionStrategy = {
      new SizeTieredCompactionStrategy(QueryBuilder.Create.bucket_low(qb, size))
    }
  }
```

The first thing that comes to my mind is offering a similar implementation for the LCS, with the right subproperties of course.

Another thing I noticed is that on the STCS you offer the `sstable_size_in_mb` option which I don't see on the [Cassandra docs](https://docs.datastax.com/en/cql/3.1/cql/cql_reference/compactSubprop.html) as a valid subproperty for that strategy, which appears to be only available for the LCS.

I would appreciate if you would point me in the right direction in case I'm missing some way to configure the subproperties for the LCS. Otherwise I'll be happy to contribute a PR with the proposed implementation.

Thanks,
Damián.

**Comment by alexflav23** [comment]
Hi @dbakarcic,

All fixed in `1.21.2`, should be on Bintray in the next hour, just waiting for CI to finish.

Regards.
