### ISSUE TITLE
Sbt assembly issue

### ISSUE THREAD

**Issue by zouzias** [websudos/phantom#405]
Following the example of phantom-dsl in

http://blog.websudos.com/2015/04/04/a-series-on-phantom-part-1-getting-started-with-phantom/

I created the following project: https://github.com/zouzias/cassandra-phantom-example . I think there is an issue with phantom-dsl version `1.21.0` when using `sbt assembly`. More precisely, having this sbt configuration

```
scalaVersion := "2.11.7"

resolvers ++= Seq(
  "Confluent" at "http://packages.confluent.io/maven/",
  "Typesafe repository snapshots" at "http://repo.typesafe.com/typesafe/snapshots/",
  "Typesafe repository releases" at "http://repo.typesafe.com/typesafe/releases/",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Twitter Repository"               at "http://maven.twttr.com",
  Resolver.bintrayRepo("websudos", "oss-releases")
)

val PhantomVersion = "1.21.0"


libraryDependencies ++= {
  Seq(
    "com.typesafe"                   % "config"                  % "1.2.1",
    "com.websudos"                   %% "phantom-dsl"            % PhantomVersion,
    "com.websudos"                   %% "phantom-testkit"        % "1.12.2" % "test, provided"
  )
}
```

You get the following error

```
[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/home/travis/.ivy2/cache/io.netty/netty-handler/jars/netty-handler-4.0.33.Final.jar:META-INF/io.netty.versions.properties
/home/travis/.ivy2/cache/io.netty/netty-buffer/jars/netty-buffer-4.0.33.Final.jar:META-INF/io.netty.versions.properties
/home/travis/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.0.33.Final.jar:META-INF/io.netty.versions.properties
/home/travis/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.0.33.Final.jar:META-INF/io.netty.versions.properties
/home/travis/.ivy2/cache/io.netty/netty-codec/jars/netty-codec-4.0.33.Final.jar:META-INF/io.netty.versions.properties
```
The above error has been reproduced using travis, here https://travis-ci.org/zouzias/cassandra-phantom-example/builds/104337405

Shouldn't `sbt assembly` with phatom-dsl as dependency work without any issues?

**Comment by alexflav23** [comment]
Hi @zouzias,

`phantom-testkit` is now deprecated so I'm not sure how your build even resolves with `1.12.2`. About this problem in particular, it's relatively outside of our control, since it's brought in by our indirect dependency on Netty.

Anyway, something like this should do the trick:

```scala
mergeStrategy in assembly := {
  case x if x.endsWith("io.netty.versions.properties") => MergeStrategy.first
}
```
I'm not 100% sure if this file is needed at runtime, because if it isn't you can also use `MergeStrategy.discard`. Hope this helps.

**Comment by zouzias** [comment]
Hi @alexflav23 ,

Thank you for the prompt reply. 

Didn't know that `phantom-testkit` is deprecated.

I think it might be a good idea to document the above merge strategy for those using `sbt assembly`. We also resolved the problem with the same mergeStrategy, see https://github.com/zouzias/cassandra-phantom-example/blob/master/build.sbt

**Comment by z160896** [comment]
your suggestion doesn't work for me. this problem occurs when I changed to "com.amazonaws" % "aws-java-sdk" % "1.11.368", from "com.amazonaws" % "aws-java-sdk" % "1.7.7",

I use the plugin version: addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.7")
Intellij scala 2.11.12.

Any suggestions to fix this problem?
[error] 1 error was encountered during merge
[error] java.lang.RuntimeException: deduplicate: different file contents found in the following:
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-codec-http\jars\netty-codec-http-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-codec\jars\netty-codec-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-transport\jars\netty-transport-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-buffer\jars\netty-buffer-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-common\jars\netty-common-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-resolver\jars\netty-resolver-4.1.17.Final.jar:META-INF/io.netty.versions.properties
[error] C:\Users\rzhou\.ivy2\cache\io.netty\netty-handler\jars\netty-handler-4.1.17.Final.jar:META-INF/io.netty.versions.properties

**Comment by nextdtinc** [comment]
I have the same problem. Has anyone found a solution?
