### ISSUE TITLE
Cannot add multiple Where clauses when creating a PreparedStatement 

### ISSUE THREAD

**Issue by sbrnunes** [websudos/phantom#407]
Hi,

I'm getting the error bellow when trying to create a prepared statement with multiple where clauses, using Phantom:
```
update.p_where(_.column1 eqs ?).p_and(_.column2 eqs ?).p_modify(_.solumn3 setTo ?).prepare()
```

The error:
```
Error:(53, 11) Cannot prove that com.websudos.phantom.builder.Chainned =:= com.websudos.phantom.builder.Unchainned.
    .p_and(_.UserId eqs ?)
          ^
```

I suspect the problem is in the implicit declared in the `p_and` method, in the `UpdateQuery` class:
```
def p_and[RR](condition: Table => PreparedWhereClause.ParametricCondition[RR])
    (implicit ev: Chain =:= Unchainned): UpdateQuery[Table, Record, Limit, Order, Status, Chainned, RR :: PS] = {
    ...
    )
  }
```

Shoul it be `=:= Chained` instead of `=:= Unchained` ?

**Comment by alexflav23** [comment]
@sbrnunes,

Indeed, you have indicated the correct error. Any chance you could submit a PR for this and I'll do a release for you?

Regards.

**Comment by sbrnunes** [comment]
Ok, I'll probably need a couple of hours to set-up the project, make the fix and ensure I don't break any tests. I'll keep you posted.
Thanks.

**Comment by alexflav23** [comment]
Hi @sbrnunes, I've already done it, many thanks though. I had a spare 2 minutes and took advantage of it.

**Comment by sbrnunes** [comment]
Ok, thanks a lot for that. Appreciated. :)

**Comment by alexflav23** [comment]
Hi @sbrnunes , `1.21.3` is already on Bintray. Happy to hear phantom made its way to Zendesk.(if that's the case).
