### ISSUE TITLE
prepare statement bind is failing with custom types

### ISSUE THREAD

**Issue by lahirug** [websudos/phantom#409]
I have introduced new type and tried to insert it with a prepare statement and it failed with this error,

com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [timestamp <-> java.time.OffsetDateTime]

But when I just do an insert it worked without prepare-statement. I wonder what am I missing.

**Comment by alexflav23** [comment]
You need to add a new codec in the `CodecRegistry`. This is to do with how the Java driver prepares statements, not much to do with phantom unfortunately. I will look for an example somewhere, but just look at the registry and you should be able to infer what needs to be done.

**Comment by lahirug** [comment]
Looks like I have to write java code to get this working ? Or is there a way to deal with this by writing the codec in Scala but I don't find any useful docs on that topic.

**Comment by lahirug** [comment]
I wrote the Codec and I have the custom type defined as below,
  /** OffsetDateTime in Cassandra (in the configured timezone), consider also storing the timezone offset */
  implicit object OffsetDateTimePrimitive extends Primitive[OffsetDateTime] {
    override type PrimitiveType = Date
    val cassandraType = CQLSyntax.Types.Timestamp
    def fromRow(row: Row, name: String): Option[OffsetDateTime] = fromRow(name, row).toOption
    override def asCql(value: OffsetDateTime): String = {
      CQLQuery.escape(DateTimeFormatter.ISO_INSTANT.format(value.atZoneSameInstant(AnalyticsZone)))
    }
    override def fromRow(column: String, row: Row): Try[OffsetDateTime] = nullCheck(column, row) {
      r => OffsetDateTime.ofInstant(r.getTimestamp(column).toInstant, AnalyticsZone)
    }
    override def fromString(value: String): OffsetDateTime = OffsetDateTime.parse(value)
    override def clz: Class[Date] = classOf[Date]
  }

  type OptionalOffsetDateTimeColumn[Owner <: CassandraTable[Owner, Record], Record] = OptionalPrimitiveColumn[Owner, Record, OffsetDateTime]


But when I try to get it as a user type during startup I get null and there are no user_types returns in below code.

val codecRegistry = CodecRegistry.DEFAULT_INSTANCE
    val offsetDateTimeType = session.getCluster.getMetadata.getKeyspace(CassandraDB(system).connector.name).getUserType("OffsetDateTime")

**Comment by lahirug** [comment]
Thanks Alex, was able to resolve it by writing Codecs.
