### ISSUE TITLE
Problem with insert Double into DoubleColumn

### ISSUE THREAD

**Issue by uover82** [websudos/phantom#415]
Hi,
I'm working with scala 2.10/phantom 1.21, and getting the following error when attempting to insert a Double model value into a service DoubleColumn:

[ERROR] /opt/Sylvester/feed/src/main/scala/org/apache/spark/feed/service/CassandraSvcs.scala:144: type mismatch;
 found   : org.apache.spark.feed.model.LocationModel => x$57.latitude.type forSome { val x$57: org.apache.spark.feed.model.LocationModel }
 required: org.apache.spark.feed.model.LocationModel => com.websudos.phantom.column.AbstractColumn[Any]
[ERROR]           .value(_.latitude, crime.getLocation_1.getLatitude)

Any ideas/ comments? 

Thanks!

John

**Comment by alexflav23** [comment]
Hi @uover82 ,

You are obviously providing the wrong type, `getLatitude` is not returning a double.

Regards.

**Comment by uover82** [comment]
Hi Flavian,


Thank you for your help [&#X1f60a]


Things are a little complicated in that I've also integrated Socrata/soda-java for api access - I'll explain:


The insert looks like:


        locationModel.insert
          .value(_.id, location_id)
          .value(_.latitude, crime.getLocation_1.getLatitude)
          .value(_.longitude, crime.getLocation_1.getLongitude)
          .value(_.address_id, address_id)
          .statement()
          .runWith(ConsistencyLevel.QUORUM)


Location bean (soja-java) like this:


    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

model is like this:

  object latitude extends DoubleColumn(this)
  object longitude extends DoubleColumn(this)


entity is like this:


  latitude: Double,
  longitude: Double,


Should the underlying bean return double or Double?


Thanks


John

________________________________

**Comment by alexflav23** [comment]
It's simple, `scala.Double` is not the same as `java.lang.Double`. Use `getLongitude.doubleValue`, the `doubleValue` part should come from Scala automatically as an implicit value class augmentation.

**Comment by uover82** [comment]
Works like a charm, Flavian [&#X1f60a]  Thanks for the insight!


John

________________________________
