### ISSUE TITLE
How can I pull down phantom in sbt?  Readme needs an example.

### ISSUE THREAD

**Issue by gzoller** [websudos/phantom#416]
I'm trying to get phantom without much luck.  From Sonatype version 1.20.0 and 1.21.0 are there but the jar file is empty.  On bintray there are lots more versions but I can't guess the group etc. to get sbt to download them?

Can this be added to the beginning of the readme document?  Just need a simple cut 'n paste example 1-liner for sbt for both of your 2 delivery methods.

Thanks!

**Comment by alexflav23** [comment]
https://github.com/websudos/phantom/wiki/Integrating-phantom-in-your-project

**Comment by alexflav23** [comment]
Hi @gzoller,

We have moved most of the documentation to the GitHub Wiki pages, our reasoning being quite simple. We can update the Wiki immediately at any time, without needing to merge pull requests, run CI builds, etc.

In the future, odds are most of the things you are looking for are addressed in the wiki. Hope this helps.

Regards,
Flavian
