### ISSUE TITLE
Select distinct without fields compiles and generates invalid query

### ISSUE THREAD

**Issue by tabdulradi** [websudos/phantom#420]
This is Scala code
`table.select.distinct.fetch`

Generates this invalid CQL query, which of course fails at Cassandra side
`SELECT DISTINCT  FROM my_keyspace.my_table;`
Note: this is two spaces between DISTINCT and FROM

Expected behaviour: The code shouldn't compile unless I specify only static fields. 

I am using version 1.21.0

**Comment by alexflav23** [comment]
Hi @tabdulradi ,

Thank you for your bug report, we will trace this up and release a fix shortly.

Regards.

**Comment by alexflav23** [comment]
Hi @tabdulradi ,

This is now fixed in `1.22.0` which should go live today.

Regards.
