### ISSUE TITLE
Issue with Maven central Repo SBT version syntax

### ISSUE THREAD

**Issue by dan-mi-sun** [websudos/phantom#424]
http://search.maven.org/#artifactdetails|com.websudos|phantom_2.10|1.22.0|

Currently reads:
libraryDependencies += "com.websudos" % "phantom_2.10" % "1.22.0"

Should read:

libraryDependencies +="com.websudos" % "phantom-dsl_2.10" % "1.22.0"

**Comment by alexflav23** [comment]
Hi @dan-mi-sun ,

This is obviously the published version of the root artifact which is included by default, it's not an error.  You can't expect for Maven Central to have contextual awareness.

Regards.
