### ISSUE TITLE
Create Index Over ListColumn

### ISSUE THREAD

**Issue by abhitechdojo** [websudos/phantom#430]
I can create an index easily when the data type is a primitive data type

`object year extends IntColumn(this) with Index[Int]`

but how to index a column when its type is ListColumn. like

`object genre extends ListColumn(this)`

**Comment by alexflav23** [comment]
Hi @abhitechdojo,

As far as I'm aware you can only do `contains` queries with secondary indexes on `Set` columns, not `List`.

Here's what you do: `object genre extends SetColumn[Table, Record, Int](this) with Index[Set[Int]]`

Hope this makes sense. Careful with `ListColumn` too, all collection columns need the `TableType` and `RecordType` arguments.

Look at [this test](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/db/specialized/IndexedCollectionsTest.scala) for examples on using indexed collections, and then at [this table](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/tables/IndexedCollectionsTable.scala) for an example on how to define such tables.

Regards.

**Comment by abhitechdojo** [comment]
I think new version of cassandra allows set index on lists

`create table Movies (
  id int primary key,
  title text,
  year int,
  genre list<text>
);
create index on Movies(year);
create index on Movies(genre);
cqlsh:movielens> insert into movies(id, genre, title, year) values(1, ['comedy', 'action'], 'policy story', 1985);
cqlsh:movielens> select * from movies where genre contains 'comedy';

 id | genre                | title        | year
----+----------------------+--------------+------
  1 | ['comedy', 'action'] | policy story | 1985`
